"""
NOVA Advanced Game Generator
"""

import os

PROJECTS = os.path.expanduser("~/NOVA/generated_projects")


def create_game(name):

    folder = os.path.join(
        PROJECTS,
        name.replace(" ", "_").lower()
    )

    os.makedirs(folder, exist_ok=True)

    for d in [
        "assets",
        "images",
        "sounds",
        "levels"
    ]:
        os.makedirs(
            os.path.join(folder, d),
            exist_ok=True
        )

    files = {

        "main.py":
'''from player import Player
from enemy import Enemy

print("Starting Game")

player = Player()
enemy = Enemy()

print("Game Loaded")
''',

        "player.py":
'''class Player:

    def __init__(self):

        self.name = "Player"

        self.health = 100

        self.score = 0

    def move(self):

        print("Player moved")
''',

        "enemy.py":
'''class Enemy:

    def __init__(self):

        self.health = 50

    def attack(self):

        print("Enemy attacks")
''',

        "settings.py":
'''WIDTH = 800

HEIGHT = 600

FPS = 60
''',

        "README.md":
f'''# {name}

Generated by NOVA

Run:

python main.py
''',

        "requirements.txt":
'''pygame
'''
    }

    for filename, content in files.items():

        with open(
            os.path.join(folder, filename),
            "w"
        ) as f:

            f.write(content)

    return f"{name} created successfully."


advanced_game = create_game
