import os


class AIBuilder:

    def write(self, filename, code):

        with open(filename, "w", encoding="utf-8") as f:
            f.write(code)


    def create_project(self, name):

        os.makedirs(name, exist_ok=True)

        readme = f"""# {name}

Generated by NOVA

Install any required Python packages before running.
"""

        self.write(f"{name}/README.md", readme)

        return f"{name} created."


    # =========================================
    # CHATBOT
    # =========================================

    def create_chatbot(self):

        self.create_project("ai_chatbot")

        code = '''
print("NOVA AI Chatbot")

while True:

    user = input("You: ")

    if user.lower() == "exit":

        break

    print("NOVA:", "I am learning.")
'''

        self.write("ai_chatbot/main.py", code)

        return "AI Chatbot created."


    # =========================================
    # VOICE ASSISTANT
    # =========================================

    def create_voice_assistant(self):

        self.create_project("voice_assistant")

        code = '''
print("Voice Assistant Started")
'''

        self.write("voice_assistant/main.py", code)

        return "Voice Assistant created."


    # =========================================
    # TEXT SUMMARIZER
    # =========================================

    def create_summarizer(self):

        self.create_project("text_summarizer")

        code = '''
text=input("Text: ")

print(text[:200])
'''

        self.write("text_summarizer/main.py", code)

        return "Summarizer created."


    # =========================================
    # TRANSLATOR
    # =========================================

    def create_translator(self):

        self.create_project("translator")

        code = '''
print("Translator Template")
'''

        self.write("translator/main.py", code)

        return "Translator created."


    # =========================================
    # OCR
    # =========================================

    def create_ocr(self):

        self.create_project("ocr")

        code = '''
print("OCR Template")
'''

        self.write("ocr/main.py", code)

        return "OCR project created."


    # =========================================
    # IMAGE CLASSIFIER
    # =========================================

    def create_image_classifier(self):

        self.create_project("image_classifier")

        code = '''
print("Image Classifier")
'''

        self.write("image_classifier/main.py", code)

        return "Image Classifier created."


    # =========================================
    # OBJECT DETECTOR
    # =========================================

    def create_object_detector(self):

        self.create_project("object_detector")

        code = '''
print("Object Detector")
'''

        self.write("object_detector/main.py", code)

        return "Object Detector created."


    # =========================================
    # FACE DETECTOR
    # =========================================

    def create_face_detector(self):

        self.create_project("face_detector")

        code = '''
print("Face Detector")
'''

        self.write("face_detector/main.py", code)

        return "Face Detector created."


    # =========================================
    # SPEECH TO TEXT
    # =========================================

    def create_speech_to_text(self):

        self.create_project("speech_to_text")

        code = '''
print("Speech To Text")
'''

        self.write("speech_to_text/main.py", code)

        return "Speech To Text created."


    # =========================================
    # TEXT TO SPEECH
    # =========================================

    def create_text_to_speech(self):

        self.create_project("text_to_speech")

        code = '''
print("Text To Speech")
'''

        self.write("text_to_speech/main.py", code)

        return "Text To Speech created."


    # =========================================
    # SENTIMENT ANALYSIS
    # =========================================

    def create_sentiment(self):

        self.create_project("sentiment_analysis")

        code = '''
print("Sentiment Analysis")
'''

        self.write("sentiment_analysis/main.py", code)

        return "Sentiment Analysis created."


    # =========================================
    # RECOMMENDATION SYSTEM
    # =========================================

    def create_recommendation(self):

        self.create_project("recommendation_system")

        code = '''
print("Recommendation System")
'''

        self.write("recommendation_system/main.py", code)

        return "Recommendation System created."
