"""
NOVA AI Generator
Creates starter AI projects.
"""

import os

PROJECTS = os.path.expanduser("~/NOVA/generated_projects")

os.makedirs(PROJECTS, exist_ok=True)


def create_ai_project(name, description):

    folder = os.path.join(
        PROJECTS,
        name.replace(" ", "_").lower()
    )

    os.makedirs(folder, exist_ok=True)

    code = f'''"""
{name}
Generated by NOVA
"""

class AI:

    def __init__(self):
        self.name = "{name}"

    def run(self):

        print("Starting {{}}".format(self.name))
        print("{description}")


if __name__ == "__main__":

    AI().run()
'''

    with open(
        os.path.join(folder, "main.py"),
        "w"
    ) as file:

        file.write(code)

    return f"{name} created successfully in {folder}"


def coding_assistant():
    return create_ai_project(
        "Coding Assistant",
        "AI that helps write and explain code."
    )


def voice_assistant():
    return create_ai_project(
        "Voice Assistant",
        "AI that listens and responds to voice commands."
    )


def image_assistant():
    return create_ai_project(
        "Image Assistant",
        "AI for image generation and editing."
    )


def video_assistant():
    return create_ai_project(
        "Video Assistant",
        "AI for video creation and editing."
    )


def trading_assistant():
    return create_ai_project(
        "Trading Assistant",
        "AI that analyzes financial markets."
    )


def teacher_assistant():
    return create_ai_project(
        "Teacher Assistant",
        "AI that teaches programming and science."
    )
