import os


class AndroidBuilder:

    def write(self, filename, code):

        with open(filename, "w", encoding="utf-8") as f:
            f.write(code)


    def create_project(self, name):

        os.makedirs(name, exist_ok=True)
        os.makedirs(f"{name}/app", exist_ok=True)
        os.makedirs(f"{name}/app/src", exist_ok=True)
        os.makedirs(f"{name}/app/src/main", exist_ok=True)
        os.makedirs(f"{name}/app/src/main/java", exist_ok=True)
        os.makedirs(f"{name}/app/src/main/res/layout", exist_ok=True)
        os.makedirs(f"{name}/app/src/main/res/values", exist_ok=True)

        manifest = '''<?xml version="1.0" encoding="utf-8"?>
<manifest package="com.NOVA.app">

<application

android:label="NOVA App">

<activity android:name=".MainActivity">

<intent-filter>

<action android:name="android.intent.action.MAIN"/>

<category android:name="android.intent.category.LAUNCHER"/>

</intent-filter>

</activity>

</application>

</manifest>
'''

        activity = '''package com.NOVA.app;

public class MainActivity {

    public static void main(String[] args){

        System.out.println("Welcome to NOVA Android");

    }

}
'''

        layout = '''<?xml version="1.0" encoding="utf-8"?>

<LinearLayout

xmlns:android="http://schemas.android.com/apk/res/android"

android:orientation="vertical"

android:layout_width="match_parent"

android:layout_height="match_parent">

<TextView

android:layout_width="wrap_content"

android:layout_height="wrap_content"

android:text="Hello from NOVA"/>

</LinearLayout>
'''

        strings = '''<resources>

<string name="app_name">NOVA</string>

</resources>
'''

        gradle = '''plugins{

id "com.android.application"

}

android{

compileSdk 35

defaultConfig{

applicationId "com.NOVA.app"

minSdk 24

targetSdk 35

versionCode 1

versionName "1.0"

}

}
'''

        readme = f'''# {name}

Generated by NOVA

Open this project in Android Studio.

Build and run the app.
'''

        self.write(f"{name}/AndroidManifest.xml", manifest)
        self.write(f"{name}/build.gradle", gradle)
        self.write(f"{name}/app/src/main/java/MainActivity.java", activity)
        self.write(f"{name}/app/src/main/res/layout/activity_main.xml", layout)
        self.write(f"{name}/app/src/main/res/values/strings.xml", strings)
        self.write(f"{name}/README.md", readme)

        return f"Android project '{name}' created."


    def create_chat_app(self):
        return self.create_project("android_chat")


    def create_music_player(self):
        return self.create_project("android_music")


    def create_video_player(self):
        return self.create_project("android_video")


    def create_browser(self):
        return self.create_project("android_browser")


    def create_calculator(self):
        return self.create_project("android_calculator")


    def create_notes(self):
        return self.create_project("android_notes")


    def create_school(self):
        return self.create_project("android_school")


    def create_bank(self):
        return self.create_project("android_bank")


    def create_store(self):
        return self.create_project("android_store")


    def create_ai(self):
        return self.create_project("android_ai")
