"""
NOVA API Generator
"""

import os

PROJECTS = os.path.expanduser("~/NOVA/generated_projects")

os.makedirs(PROJECTS, exist_ok=True)


def create_api(name):

    folder = os.path.join(
        PROJECTS,
        name.replace(" ", "_").lower()
    )

    os.makedirs(folder, exist_ok=True)

    app = '''from flask import Flask

app = Flask(__name__)

@app.route("/")
def home():
    return {
        "name": "NOVA API",
        "status": "online"
    }

@app.route("/hello")
def hello():
    return {
        "message": "Hello from NOVA!"
    }

if __name__ == "__main__":
    app.run(debug=True)
'''

    requirements = '''Flask
'''

    readme = f'''# {name}

Generated by NOVA

## Install

pip install -r requirements.txt

## Run

python app.py
'''

    with open(os.path.join(folder, "app.py"), "w") as f:
        f.write(app)

    with open(os.path.join(folder, "requirements.txt"), "w") as f:
        f.write(requirements)

    with open(os.path.join(folder, "README.md"), "w") as f:
        f.write(readme)

    return f"API '{name}' created successfully in {folder}"


def flask_api():
    return create_api("Flask API")


def rest_api():
    return create_api("REST API")


def NOVA_api():
    return create_api("NOVA API")
