import os


class APIBuilder:

    def write(self, filename, code):

        with open(filename, "w", encoding="utf-8") as f:
            f.write(code)


    def create_project(self, name):

        os.makedirs(name, exist_ok=True)

        readme = f"""# {name}

Generated by NOVA

REST API Project
"""

        self.write(f"{name}/README.md", readme)

        return f"{name} created."


    # ==========================================
    # BASIC REST API
    # ==========================================

    def create_rest_api(self):

        self.create_project("rest_api")

        code = '''
from flask import Flask, request, jsonify

app = Flask(__name__)

items = []

@app.get("/")
def home():

    return jsonify({"message":"NOVA REST API"})


@app.get("/items")
def get_items():

    return jsonify(items)


@app.post("/items")
def add_item():

    data = request.json

    items.append(data)

    return jsonify({"status":"added","item":data})


@app.put("/items/<int:index>")
def update_item(index):

    if index >= len(items):

        return jsonify({"error":"Not found"}),404

    items[index] = request.json

    return jsonify(items[index])


@app.delete("/items/<int:index>")
def delete_item(index):

    if index >= len(items):

        return jsonify({"error":"Not found"}),404

    items.pop(index)

    return jsonify({"status":"deleted"})


app.run()
'''

        self.write("rest_api/main.py", code)

        return "REST API created."


    # ==========================================
    # USER API
    # ==========================================

    def create_user_api(self):

        return self.create_project("user_api")


    # ==========================================
    # SCHOOL API
    # ==========================================

    def create_school_api(self):

        return self.create_project("school_api")


    # ==========================================
    # CHAT API
    # ==========================================

    def create_chat_api(self):

        return self.create_project("chat_api")


    # ==========================================
    # BANK API
    # ==========================================

    def create_bank_api(self):

        return self.create_project("bank_api")


    # ==========================================
    # STORE API
    # ==========================================

    def create_store_api(self):

        return self.create_project("store_api")


    # ==========================================
    # INVENTORY API
    # ==========================================

    def create_inventory_api(self):

        return self.create_project("inventory_api")


    # ==========================================
    # TODO API
    # ==========================================

    def create_todo_api(self):

        return self.create_project("todo_api")


    # ==========================================
    # NOTES API
    # ==========================================

    def create_notes_api(self):

        return self.create_project("notes_api")


    # ==========================================
    # WEATHER API
    # ==========================================

    def create_weather_api(self):

        return self.create_project("weather_api")


    # ==========================================
    # AI API
    # ==========================================

    def create_ai_api(self):

        return self.create_project("ai_api")


    # ==========================================
    # TRADING API
    # ==========================================

    def create_trading_api(self):

        return self.create_project("trading_api")


    # ==========================================
    # PAYMENT API
    # ==========================================

    def create_payment_api(self):

        return self.create_project("payment_api")


    # ==========================================
    # AUTH API
    # ==========================================

    def create_auth_api(self):

        return self.create_project("auth_api")


    # ==========================================
    # IMAGE API
    # ==========================================

    def create_image_api(self):

        return self.create_project("image_api")


    # ==========================================
    # VIDEO API
    # ==========================================

    def create_video_api(self):

        return self.create_project("video_api")


    # ==========================================
    # MUSIC API
    # ==========================================

    def create_music_api(self):

        return self.create_project("music_api")
