# ==========================================================
# NOVA APP BUILDER v1.0
# GENERAL APPLICATION PROJECT BUILDER
# ==========================================================

from pathlib import Path
import re


class AppBuilder:

    def __init__(self, root=None):

        if root is None:
            root = (
                Path(__file__).resolve().parent.parent
                / "GeneratedProjects"
                / "Apps"
            )

        self.root = Path(root)
        self.root.mkdir(
            parents=True,
            exist_ok=True
        )

    # ======================================================
    # CLEAN PROJECT NAME
    # ======================================================

    def clean_name(self, name):

        name = str(name).strip()

        name = re.sub(
            r"[^a-zA-Z0-9_-]+",
            "_",
            name
        )

        name = name.strip("_-")

        return name or "NOVAApp"

    # ======================================================
    # CREATE PROJECT
    # ======================================================

    def create(self, name):

        name = self.clean_name(name)

        project = self.root / name

        directories = [
            "src",
            "src/core",
            "src/ui",
            "src/services",
            "src/models",
            "assets",
            "config",
            "data",
            "tests",
            "docs"
        ]

        for directory in directories:

            (
                project / directory
            ).mkdir(
                parents=True,
                exist_ok=True
            )

        files = {

            "README.md":
                f"# {name}\n\n"
                "Generated by NOVA.\n\n"
                "General application project.\n",

            "src/main.py":
                f'''"""
{name}
Generated by NOVA.
"""


def main():

    print("{name} started.")


if __name__ == "__main__":
    main()
''',

            "src/core/app.py":
                '''"""
Main application logic.
"""


class Application:

    def start(self):

        print("Application started.")
''',

            "config/config.json":
                '''{
    "name": "NOVAApp",
    "version": "1.0.0"
}
''',

            "tests/test_app.py":
                '''def test_application():

    assert True
'''
        }

        created = []

        for relative, content in files.items():

            path = project / relative

            path.parent.mkdir(
                parents=True,
                exist_ok=True
            )

            path.write_text(
                content,
                encoding="utf-8"
            )

            created.append(relative)

        return {
            "success": True,
            "project": name,
            "path": str(project),
            "type": "app",
            "files": created
        }


# ==========================================================
# SIMPLE FUNCTION
# ==========================================================

def build_app(name):

    builder = AppBuilder()

    return builder.create(name)


# ==========================================================
# TEST
# ==========================================================

if __name__ == "__main__":

    result = build_app(
        "TestApp"
    )

    print(
        "App created:"
    )

    print(
        result["path"]
    )

    for file in result["files"]:

        print(
            "-",
            file
        )
