import os


class AssistantBuilder:

    def write(self, filename, code):

        os.makedirs(os.path.dirname(filename), exist_ok=True)

        with open(filename, "w", encoding="utf-8") as f:

            f.write(code)


    def create_project(self, name):

        os.makedirs(name, exist_ok=True)

        self.write(

            f"{name}/README.md",

            f"# {name}\n\nGenerated by NOVA\n"

        )

        return f"{name} created."


    # ==========================================
    # VOICE ASSISTANT
    # ==========================================

    def create_voice_assistant(self):

        self.create_project("voice_assistant")

        code = '''
print("NOVA Voice Assistant")
'''

        self.write("voice_assistant/main.py", code)

        return "Voice Assistant created."


    # ==========================================
    # WAKE WORD
    # ==========================================

    def create_wake_word(self):

        self.create_project("wake_word")

        code = '''
WAKE_WORD = "NOVA wake up"

print("Wake word:", WAKE_WORD)
'''

        self.write("wake_word/main.py", code)

        return "Wake Word module created."


    # ==========================================
    # MEMORY
    # ==========================================

    def create_memory(self):

        self.create_project("memory_system")

        code = '''
memory = {}

def remember(key,value):

    memory[key]=value

def recall(key):

    return memory.get(key)
'''

        self.write("memory_system/main.py", code)

        return "Memory System created."


    # ==========================================
    # SCHEDULER
    # ==========================================

    def create_scheduler(self):

        self.create_project("scheduler")

        code = '''
print("NOVA Scheduler")
'''

        self.write("scheduler/main.py", code)

        return "Scheduler created."


    # ==========================================
    # PLUGIN SYSTEM
    # ==========================================

    def create_plugins(self):

        self.create_project("plugins")

        code = '''
print("Plugin System")
'''

        self.write("plugins/main.py", code)

        return "Plugin System created."


    # ==========================================
    # SELF UPDATE
    # ==========================================

    def create_updater(self):

        self.create_project("updater")

        code = '''
print("NOVA Updater")
'''

        self.write("updater/main.py", code)

        return "Updater created."


    # ==========================================
    # LEARNING ENGINE
    # ==========================================

    def create_learning(self):

        self.create_project("learning_engine")

        code = '''
print("NOVA Learning Engine")
'''

        self.write("learning_engine/main.py", code)

        return "Learning Engine created."


    # ==========================================
    # CODE GENERATOR
    # ==========================================

    def create_code_generator(self):

        self.create_project("code_generator")

        code = '''
print("NOVA Code Generator")
'''

        self.write("code_generator/main.py", code)

        return "Code Generator created."


    # ==========================================
    # PROJECT GENERATOR
    # ==========================================

    def create_project_generator(self):

        self.create_project("project_generator")

        code = '''
print("NOVA Project Generator")
'''

        self.write("project_generator/main.py", code)

        return "Project Generator created."


    # ==========================================
    # SELF DIAGNOSTICS
    # ==========================================

    def create_diagnostics(self):

        self.create_project("diagnostics")

        code = '''
print("Running NOVA Diagnostics")
'''

        self.write("diagnostics/main.py", code)

        return "Diagnostics created."
