"""
NOVA Automation Generator
Creates Python automation scripts.
"""

import os

PROJECTS = os.path.expanduser("~/NOVA/generated_projects")

os.makedirs(PROJECTS, exist_ok=True)


def create_automation(name):

    folder = os.path.join(
        PROJECTS,
        name.replace(" ", "_").lower()
    )

    os.makedirs(folder, exist_ok=True)

    code = '''"""
Automation Script
Generated by NOVA
"""

import os
import shutil
from datetime import datetime


def backup_folder(source, destination):

    if not os.path.exists(source):
        print("Source folder not found.")
        return

    os.makedirs(destination, exist_ok=True)

    backup_name = datetime.now().strftime("%Y%m%d_%H%M%S")

    backup_path = os.path.join(
        destination,
        backup_name
    )

    shutil.copytree(source, backup_path)

    print("Backup completed:", backup_path)


if __name__ == "__main__":

    print("NOVA Automation Ready")
'''

    with open(
        os.path.join(folder, "main.py"),
        "w"
    ) as file:

        file.write(code)

    return f"Automation project '{name}' created successfully in {folder}"


def backup_script():
    return create_automation("Backup Script")


def file_organizer():
    return create_automation("File Organizer")


def folder_watcher():
    return create_automation("Folder Watcher")


def task_scheduler():
    return create_automation("Task Scheduler")


def web_scraper():
    return create_automation("Web Scraper")


def email_sender():
    return create_automation("Email Sender")
