import os


class AutomationBuilder:

    def write(self, filename, code):

        os.makedirs(os.path.dirname(filename), exist_ok=True)

        with open(filename, "w", encoding="utf-8") as f:
            f.write(code)


    def create_project(self, name):

        os.makedirs(name, exist_ok=True)

        self.write(
            f"{name}/README.md",
            f"# {name}\n\nGenerated by NOVA\n"
        )

        return f"{name} created."


    # ==========================================
    # FILE ORGANIZER
    # ==========================================

    def create_file_organizer(self):

        self.create_project("file_organizer")

        code = '''
import os

print("NOVA File Organizer")
'''

        self.write("file_organizer/main.py", code)

        return "File Organizer created."


    # ==========================================
    # BACKUP TOOL
    # ==========================================

    def create_backup(self):

        self.create_project("backup_tool")

        code = '''
print("NOVA Backup Tool")
'''

        self.write("backup_tool/main.py", code)

        return "Backup Tool created."


    # ==========================================
    # RENAME FILES
    # ==========================================

    def create_bulk_rename(self):

        self.create_project("bulk_rename")

        code = '''
print("NOVA Bulk Rename")
'''

        self.write("bulk_rename/main.py", code)

        return "Bulk Rename created."


    # ==========================================
    # PDF TOOL
    # ==========================================

    def create_pdf_tool(self):

        self.create_project("pdf_tool")

        code = '''
print("NOVA PDF Tool")
'''

        self.write("pdf_tool/main.py", code)

        return "PDF Tool created."


    # ==========================================
    # IMAGE TOOL
    # ==========================================

    def create_image_tool(self):

        self.create_project("image_tool")

        code = '''
print("NOVA Image Tool")
'''

        self.write("image_tool/main.py", code)

        return "Image Tool created."


    # ==========================================
    # VIDEO TOOL
    # ==========================================

    def create_video_tool(self):

        self.create_project("video_tool")

        code = '''
print("NOVA Video Tool")
'''

        self.write("video_tool/main.py", code)

        return "Video Tool created."


    # ==========================================
    # MUSIC TOOL
    # ==========================================

    def create_music_tool(self):

        self.create_project("music_tool")

        code = '''
print("NOVA Music Tool")
'''

        self.write("music_tool/main.py", code)

        return "Music Tool created."


    # ==========================================
    # EMAIL AUTOMATION
    # ==========================================

    def create_email_tool(self):

        self.create_project("email_tool")

        code = '''
print("NOVA Email Automation")
'''

        self.write("email_tool/main.py", code)

        return "Email Tool created."


    # ==========================================
    # SCHEDULER
    # ==========================================

    def create_scheduler(self):

        self.create_project("automation_scheduler")

        code = '''
print("NOVA Automation Scheduler")
'''

        self.write("automation_scheduler/main.py", code)

        return "Automation Scheduler created."


    # ==========================================
    # WEB SCRAPER
    # ==========================================

    def create_web_scraper(self):

        self.create_project("web_scraper")

        code = '''
print("NOVA Web Scraper")
'''

        self.write("web_scraper/main.py", code)

        return "Web Scraper created."
