import os


class BlockchainBuilder:

    def write(self, filename, code):

        os.makedirs(os.path.dirname(filename), exist_ok=True)

        with open(filename, "w", encoding="utf-8") as f:
            f.write(code)


    def create_project(self, name):

        os.makedirs(name, exist_ok=True)

        self.write(
            f"{name}/README.md",
            f"# {name}\n\nGenerated by NOVA Blockchain Builder\n"
        )

        return f"{name} created."


    # ==========================================
    # BLOCKCHAIN
    # ==========================================

    def create_blockchain(self):

        self.create_project("blockchain")

        code = '''
print("Blockchain Template")
'''

        self.write("blockchain/main.py", code)

        return "Blockchain created."


    # ==========================================
    # CRYPTO WALLET
    # ==========================================

    def create_wallet(self):

        self.create_project("crypto_wallet")

        code = '''
print("Crypto Wallet Template")
'''

        self.write("crypto_wallet/main.py", code)

        return "Crypto Wallet created."


    # ==========================================
    # TOKEN PROJECT
    # ==========================================

    def create_token(self):

        self.create_project("token_project")

        code = '''
print("Token Project")
'''

        self.write("token_project/main.py", code)

        return "Token Project created."


    # ==========================================
    # SMART CONTRACT
    # ==========================================

    def create_smart_contract(self):

        self.create_project("smart_contract")

        contract = '''
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.20;

contract NOVAStorage {

    string public message = "Hello NOVA";

}
'''

        self.write("smart_contract/NOVAStorage.sol", contract)

        return "Smart Contract created."


    # ==========================================
    # NFT PROJECT
    # ==========================================

    def create_nft(self):

        self.create_project("nft_project")

        code = '''
print("NFT Project Template")
'''

        self.write("nft_project/main.py", code)

        return "NFT Project created."


    # ==========================================
    # DAPP
    # ==========================================

    def create_dapp(self):

        self.create_project("dapp")

        code = '''
print("Decentralized App Template")
'''

        self.write("dapp/main.py", code)

        return "DApp created."


    # ==========================================
    # ETHEREUM
    # ==========================================

    def create_ethereum(self):

        self.create_project("ethereum")

        code = '''
print("Ethereum Template")
'''

        self.write("ethereum/main.py", code)

        return "Ethereum Project created."


    # ==========================================
    # BITCOIN
    # ==========================================

    def create_bitcoin(self):

        self.create_project("bitcoin")

        code = '''
print("Bitcoin Template")
'''

        self.write("bitcoin/main.py", code)

        return "Bitcoin Project created."


    # ==========================================
    # EXCHANGE
    # ==========================================

    def create_exchange(self):

        self.create_project("crypto_exchange")

        code = '''
print("Crypto Exchange Template")
'''

        self.write("crypto_exchange/main.py", code)

        return "Crypto Exchange created."


    # ==========================================
    # PORTFOLIO TRACKER
    # ==========================================

    def create_portfolio(self):

        self.create_project("portfolio_tracker")

        code = '''
print("Portfolio Tracker")
'''

        self.write("portfolio_tracker/main.py", code)

        return "Portfolio Tracker created."


    # ==========================================
    # BLOCK EXPLORER
    # ==========================================

    def create_block_explorer(self):

        self.create_project("block_explorer")

        code = '''
print("Block Explorer Template")
'''

        self.write("block_explorer/main.py", code)

        return "Block Explorer created."


    # ==========================================
    # DEFI PROJECT
    # ==========================================

    def create_defi(self):

        self.create_project("defi_project")

        code = '''
print("DeFi Project Template")
'''

        self.write("defi_project/main.py", code)

        return "DeFi Project created."
