import os

PROJECTS = os.path.expanduser("~/NOVA/generated_projects")

os.makedirs(PROJECTS, exist_ok=True)


def create_chatbot(name):

    folder = os.path.join(
        PROJECTS,
        name.replace(" ", "_").lower()
    )

    os.makedirs(folder, exist_ok=True)

    code = '''"""
AI Chatbot
Generated by NOVA
"""

def chatbot():

    print("NOVA Chatbot Started")

    while True:

        user = input("You: ")

        if user.lower() in ["exit", "quit"]:

            print("Bot: Goodbye!")
            break

        print("Bot:", "You said:", user)


if __name__ == "__main__":
    chatbot()
'''

    with open(
        os.path.join(folder, "main.py"),
        "w"
    ) as file:

        file.write(code)

    return f"Chatbot '{name}' created successfully in {folder}."


def ai_assistant():

    return create_chatbot("AI Assistant")


def discord_bot():

    return create_chatbot("Discord Bot")


def telegram_bot():

    return create_chatbot("Telegram Bot")


def whatsapp_bot():

    return create_chatbot("WhatsApp Bot")
