import os


class CloudBuilder:

    def write(self, filename, code):

        os.makedirs(os.path.dirname(filename), exist_ok=True)

        with open(filename, "w", encoding="utf-8") as f:
            f.write(code)


    def create_project(self, name):

        os.makedirs(name, exist_ok=True)

        self.write(
            f"{name}/README.md",
            f"# {name}\n\nGenerated by NOVA Cloud Builder\n"
        )

        return f"{name} created."


    # ==========================================
    # AWS PROJECT
    # ==========================================

    def create_aws(self):

        self.create_project("aws_project")

        code = '''
print("AWS Project Template")
'''

        self.write("aws_project/main.py", code)

        return "AWS Project created."


    # ==========================================
    # AZURE PROJECT
    # ==========================================

    def create_azure(self):

        self.create_project("azure_project")

        code = '''
print("Azure Project Template")
'''

        self.write("azure_project/main.py", code)

        return "Azure Project created."


    # ==========================================
    # GOOGLE CLOUD
    # ==========================================

    def create_google_cloud(self):

        self.create_project("google_cloud")

        code = '''
print("Google Cloud Project Template")
'''

        self.write("google_cloud/main.py", code)

        return "Google Cloud project created."


    # ==========================================
    # FIREBASE
    # ==========================================

    def create_firebase(self):

        self.create_project("firebase_project")

        code = '''
print("Firebase Project Template")
'''

        self.write("firebase_project/main.py", code)

        return "Firebase project created."


    # ==========================================
    # CLOUD STORAGE
    # ==========================================

    def create_storage(self):

        self.create_project("cloud_storage")

        code = '''
print("Cloud Storage Template")
'''

        self.write("cloud_storage/main.py", code)

        return "Cloud Storage project created."


    # ==========================================
    # SERVERLESS
    # ==========================================

    def create_serverless(self):

        self.create_project("serverless_function")

        code = '''
print("Serverless Function Template")
'''

        self.write("serverless_function/main.py", code)

        return "Serverless Function created."


    # ==========================================
    # CLOUD DATABASE
    # ==========================================

    def create_cloud_database(self):

        self.create_project("cloud_database")

        code = '''
print("Cloud Database Template")
'''

        self.write("cloud_database/main.py", code)

        return "Cloud Database created."


    # ==========================================
    # CLOUD BACKUP
    # ==========================================

    def create_backup(self):

        self.create_project("cloud_backup")

        code = '''
print("Cloud Backup Template")
'''

        self.write("cloud_backup/main.py", code)

        return "Cloud Backup created."


    # ==========================================
    # CLOUD MONITORING
    # ==========================================

    def create_monitoring(self):

        self.create_project("cloud_monitoring")

        code = '''
print("Cloud Monitoring Template")
'''

        self.write("cloud_monitoring/main.py", code)

        return "Cloud Monitoring created."


    # ==========================================
    # CLOUD DEPLOYMENT
    # ==========================================

    def create_deployment(self):

        self.create_project("cloud_deployment")

        code = '''
print("Cloud Deployment Template")
'''

        self.write("cloud_deployment/main.py", code)

        return "Cloud Deployment created."


    # ==========================================
    # KUBERNETES
    # ==========================================

    def create_kubernetes(self):

        self.create_project("kubernetes")

        code = '''
print("Kubernetes Template")
'''

        self.write("kubernetes/main.py", code)

        return "Kubernetes project created."


    # ==========================================
    # DOCKER CLOUD
    # ==========================================

    def create_docker_cloud(self):

        self.create_project("docker_cloud")

        code = '''
print("Docker Cloud Template")
'''

        self.write("docker_cloud/main.py", code)

        return "Docker Cloud project created."
