import os


class ComputerVisionBuilder:

    def write(self, filename, code):

        os.makedirs(os.path.dirname(filename), exist_ok=True)

        with open(filename, "w", encoding="utf-8") as f:
            f.write(code)


    def create_project(self, name):

        os.makedirs(name, exist_ok=True)

        self.write(
            f"{name}/README.md",
            f"# {name}\n\nGenerated by NOVA\n"
        )

        return f"{name} created."


    # ==========================================
    # IMAGE VIEWER
    # ==========================================

    def create_image_viewer(self):

        self.create_project("image_viewer")

        code = '''
import cv2

image = cv2.imread("image.jpg")

cv2.imshow("Image", image)

cv2.waitKey(0)

cv2.destroyAllWindows()
'''

        self.write("image_viewer/main.py", code)

        return "Image Viewer created."


    # ==========================================
    # WEBCAM
    # ==========================================

    def create_webcam(self):

        self.create_project("webcam")

        code = '''
import cv2

camera = cv2.VideoCapture(0)

while True:

    ok, frame = camera.read()

    if not ok:
        break

    cv2.imshow("Camera", frame)

    if cv2.waitKey(1) == 27:
        break

camera.release()

cv2.destroyAllWindows()
'''

        self.write("webcam/main.py", code)

        return "Webcam project created."


    # ==========================================
    # FACE DETECTOR
    # ==========================================

    def create_face_detector(self):

        self.create_project("face_detector")

        code = '''
print("OpenCV Face Detection Template")
'''

        self.write("face_detector/main.py", code)

        return "Face Detector created."


    # ==========================================
    # QR CODE SCANNER
    # ==========================================

    def create_qr_scanner(self):

        self.create_project("qr_scanner")

        code = '''
print("QR Scanner Template")
'''

        self.write("qr_scanner/main.py", code)

        return "QR Scanner created."


    # ==========================================
    # BARCODE SCANNER
    # ==========================================

    def create_barcode_scanner(self):

        self.create_project("barcode_scanner")

        code = '''
print("Barcode Scanner Template")
'''

        self.write("barcode_scanner/main.py", code)

        return "Barcode Scanner created."


    # ==========================================
    # OBJECT TRACKER
    # ==========================================

    def create_object_tracker(self):

        self.create_project("object_tracker")

        code = '''
print("Object Tracking Template")
'''

        self.write("object_tracker/main.py", code)

        return "Object Tracker created."


    # ==========================================
    # MOTION DETECTOR
    # ==========================================

    def create_motion_detector(self):

        self.create_project("motion_detector")

        code = '''
print("Motion Detection Template")
'''

        self.write("motion_detector/main.py", code)

        return "Motion Detector created."


    # ==========================================
    # DOCUMENT SCANNER
    # ==========================================

    def create_document_scanner(self):

        self.create_project("document_scanner")

        code = '''
print("Document Scanner Template")
'''

        self.write("document_scanner/main.py", code)

        return "Document Scanner created."


    # ==========================================
    # COLOR DETECTOR
    # ==========================================

    def create_color_detector(self):

        self.create_project("color_detector")

        code = '''
print("Color Detection Template")
'''

        self.write("color_detector/main.py", code)

        return "Color Detector created."


    # ==========================================
    # OCR
    # ==========================================

    def create_ocr(self):

        self.create_project("ocr")

        code = '''
print("OCR Template")
'''

        self.write("ocr/main.py", code)

        return "OCR project created."
