"""
NOVA Database Generator
"""

import os

PROJECTS = os.path.expanduser("~/NOVA/generated_projects")

os.makedirs(PROJECTS, exist_ok=True)


def create_database(name):

    folder = os.path.join(
        PROJECTS,
        name.replace(" ", "_").lower()
    )

    os.makedirs(folder, exist_ok=True)

    database = '''import sqlite3

connection = sqlite3.connect("database.db")

cursor = connection.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS users(

    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT,
    email TEXT

)
""")

connection.commit()

print("Database created successfully.")

connection.close()
'''

    readme = f'''# {name}

Generated by NOVA

Run:

python database.py
'''

    with open(os.path.join(folder, "database.py"), "w") as f:
        f.write(database)

    with open(os.path.join(folder, "README.md"), "w") as f:
        f.write(readme)

    return f"Database project '{name}' created successfully in {folder}"


def sqlite_database():
    return create_database("SQLite Database")


def user_database():
    return create_database("User Database")


def school_database():
    return create_database("School Database")


def ecommerce_database():
    return create_database("Ecommerce Database")
