import os


class DataScienceBuilder:

    def write(self, filename, code):

        os.makedirs(os.path.dirname(filename), exist_ok=True)

        with open(filename, "w", encoding="utf-8") as f:
            f.write(code)


    def create_project(self, name):

        os.makedirs(name, exist_ok=True)

        self.write(
            f"{name}/README.md",
            f"# {name}\n\nGenerated by NOVA Data Science Builder\n"
        )

        return f"{name} created."


    # ==========================================
    # DATA ANALYSIS
    # ==========================================

    def create_data_analysis(self):

        self.create_project("data_analysis")

        code = '''
import pandas as pd

print("Data Analysis Template")
'''

        self.write("data_analysis/main.py", code)

        return "Data Analysis created."


    # ==========================================
    # DATA VISUALIZATION
    # ==========================================

    def create_visualization(self):

        self.create_project("data_visualization")

        code = '''
import matplotlib.pyplot as plt

print("Visualization Template")
'''

        self.write("data_visualization/main.py", code)

        return "Visualization created."


    # ==========================================
    # DASHBOARD
    # ==========================================

    def create_dashboard(self):

        self.create_project("dashboard")

        code = '''
print("Dashboard Template")
'''

        self.write("dashboard/main.py", code)

        return "Dashboard created."


    # ==========================================
    # CSV ANALYZER
    # ==========================================

    def create_csv_analyzer(self):

        self.create_project("csv_analyzer")

        code = '''
import pandas as pd

print("CSV Analyzer")
'''

        self.write("csv_analyzer/main.py", code)

        return "CSV Analyzer created."


    # ==========================================
    # EXCEL ANALYZER
    # ==========================================

    def create_excel_analyzer(self):

        self.create_project("excel_analyzer")

        code = '''
import pandas as pd

print("Excel Analyzer")
'''

        self.write("excel_analyzer/main.py", code)

        return "Excel Analyzer created."


    # ==========================================
    # STATISTICS
    # ==========================================

    def create_statistics(self):

        self.create_project("statistics")

        code = '''
print("Statistics Template")
'''

        self.write("statistics/main.py", code)

        return "Statistics created."


    # ==========================================
    # NUMPY PROJECT
    # ==========================================

    def create_numpy(self):

        self.create_project("numpy_project")

        code = '''
import numpy as np

print("NumPy Template")
'''

        self.write("numpy_project/main.py", code)

        return "NumPy project created."


    # ==========================================
    # PANDAS PROJECT
    # ==========================================

    def create_pandas(self):

        self.create_project("pandas_project")

        code = '''
import pandas as pd

print("Pandas Template")
'''

        self.write("pandas_project/main.py", code)

        return "Pandas project created."


    # ==========================================
    # REPORT GENERATOR
    # ==========================================

    def create_report(self):

        self.create_project("report_generator")

        code = '''
print("Report Generator")
'''

        self.write("report_generator/main.py", code)

        return "Report Generator created."


    # ==========================================
    # DATA CLEANER
    # ==========================================

    def create_data_cleaner(self):

        self.create_project("data_cleaner")

        code = '''
print("Data Cleaner")
'''

        self.write("data_cleaner/main.py", code)

        return "Data Cleaner created."


    # ==========================================
    # DATA CONVERTER
    # ==========================================

    def create_converter(self):

        self.create_project("data_converter")

        code = '''
print("Data Converter")
'''

        self.write("data_converter/main.py", code)

        return "Data Converter created."


    # ==========================================
    # TIME SERIES
    # ==========================================

    def create_time_series(self):

        self.create_project("time_series")

        code = '''
print("Time Series Template")
'''

        self.write("time_series/main.py", code)

        return "Time Series project created."
