import os


class DatabaseBuilder:

    def write(self, filename, code):

        with open(filename, "w", encoding="utf-8") as f:
            f.write(code)


    def create_project(self, name):

        os.makedirs(name, exist_ok=True)

        readme = f"""# {name}

Generated by NOVA

Database project template.
"""

        self.write(f"{name}/README.md", readme)

        return f"{name} created."


    # =========================================
    # SQLITE DATABASE
    # =========================================

    def create_sqlite(self):

        self.create_project("sqlite_database")

        code = '''
import sqlite3

conn = sqlite3.connect("database.db")

cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS users(

id INTEGER PRIMARY KEY,

name TEXT,

email TEXT

)
""")

conn.commit()

conn.close()

print("Database created.")
'''

        self.write("sqlite_database/main.py", code)

        return "SQLite project created."


    # =========================================
    # STUDENT DATABASE
    # =========================================

    def create_student_database(self):

        self.create_project("student_database")

        code = '''
import sqlite3

db=sqlite3.connect("students.db")

cur=db.cursor()

cur.execute("""
CREATE TABLE students(

id INTEGER PRIMARY KEY,

name TEXT,

class_name TEXT,

marks INTEGER

)
""")

db.commit()

db.close()
'''

        self.write("student_database/main.py", code)

        return "Student database created."


    # =========================================
    # INVENTORY DATABASE
    # =========================================

    def create_inventory_database(self):

        self.create_project("inventory_database")

        code = '''
import sqlite3

db=sqlite3.connect("inventory.db")

cur=db.cursor()

cur.execute("""
CREATE TABLE inventory(

id INTEGER PRIMARY KEY,

item TEXT,

quantity INTEGER,

price REAL

)
""")

db.commit()

db.close()
'''

        self.write("inventory_database/main.py", code)

        return "Inventory database created."


    # =========================================
    # CONTACT DATABASE
    # =========================================

    def create_contacts_database(self):

        self.create_project("contacts_database")

        code = '''
import sqlite3

db=sqlite3.connect("contacts.db")

cur=db.cursor()

cur.execute("""
CREATE TABLE contacts(

id INTEGER PRIMARY KEY,

name TEXT,

phone TEXT

)
""")

db.commit()

db.close()
'''

        self.write("contacts_database/main.py", code)

        return "Contacts database created."


    # =========================================
    # NOTES DATABASE
    # =========================================

    def create_notes_database(self):

        self.create_project("notes_database")

        code = '''
import sqlite3

db=sqlite3.connect("notes.db")

cur=db.cursor()

cur.execute("""
CREATE TABLE notes(

id INTEGER PRIMARY KEY,

title TEXT,

content TEXT

)
""")

db.commit()

db.close()
'''

        self.write("notes_database/main.py", code)

        return "Notes database created."


    # =========================================
    # PASSWORD DATABASE
    # =========================================

    def create_password_database(self):

        self.create_project("password_database")

        code = '''
import sqlite3

db=sqlite3.connect("passwords.db")

cur=db.cursor()

cur.execute("""
CREATE TABLE passwords(

id INTEGER PRIMARY KEY,

website TEXT,

username TEXT,

password TEXT

)
""")

db.commit()

db.close()
'''

        self.write("password_database/main.py", code)

        return "Password database created."


    # =========================================
    # TODO DATABASE
    # =========================================

    def create_todo_database(self):

        self.create_project("todo_database")

        code = '''
import sqlite3

db=sqlite3.connect("todo.db")

cur=db.cursor()

cur.execute("""
CREATE TABLE todo(

id INTEGER PRIMARY KEY,

task TEXT,

completed INTEGER

)
""")

db.commit()

db.close()
'''

        self.write("todo_database/main.py", code)

        return "Todo database created."


    # =========================================
    # BANK DATABASE
    # =========================================

    def create_bank_database(self):

        self.create_project("bank_database")

        code = '''
import sqlite3

db=sqlite3.connect("bank.db")

cur=db.cursor()

cur.execute("""
CREATE TABLE accounts(

id INTEGER PRIMARY KEY,

name TEXT,

balance REAL

)
""")

db.commit()

db.close()
'''

        self.write("bank_database/main.py", code)

        return "Bank database created."
