import os


class DesktopBuilder:

    def write(self, filename, code):

        with open(filename, "w", encoding="utf-8") as f:
            f.write(code)

    def create_project(self, name):

        os.makedirs(name, exist_ok=True)

        readme = f"""# {name}

Desktop application generated by NOVA.

Run:

python main.py
"""

        self.write(f"{name}/README.md", readme)

        return f"{name} created."


    # ==========================================
    # TKINTER APP
    # ==========================================

    def create_tkinter(self):

        self.create_project("tkinter_app")

        code = '''
import tkinter as tk

root = tk.Tk()

root.title("NOVA App")

root.geometry("600x400")

label = tk.Label(
    root,
    text="Welcome to NOVA Desktop",
    font=("Arial",18)
)

label.pack(pady=20)

button = tk.Button(
    root,
    text="Close",
    command=root.destroy
)

button.pack()

root.mainloop()
'''

        self.write("tkinter_app/main.py", code)

        return "Tkinter app created."


    # ==========================================
    # NOTEPAD
    # ==========================================

    def create_notepad(self):

        self.create_project("notepad")

        code = '''
import tkinter as tk

root = tk.Tk()

root.title("NOVA Notepad")

text = tk.Text(root)

text.pack(fill="both", expand=True)

root.mainloop()
'''

        self.write("notepad/main.py", code)

        return "Notepad created."


    # ==========================================
    # CALCULATOR
    # ==========================================

    def create_calculator(self):

        self.create_project("desktop_calculator")

        code = '''
import tkinter as tk

root = tk.Tk()

root.title("Calculator")

entry = tk.Entry(root)

entry.pack(fill="x")

root.mainloop()
'''

        self.write("desktop_calculator/main.py", code)

        return "Desktop calculator created."


    # ==========================================
    # FILE MANAGER
    # ==========================================

    def create_file_manager(self):

        self.create_project("file_manager")

        code = '''
import tkinter as tk
from tkinter import filedialog

root = tk.Tk()

def open_file():

    filedialog.askopenfilename()

button = tk.Button(
    root,
    text="Open File",
    command=open_file
)

button.pack(pady=30)

root.mainloop()
'''

        self.write("file_manager/main.py", code)

        return "File manager created."


    # ==========================================
    # IMAGE VIEWER
    # ==========================================

    def create_image_viewer(self):

        self.create_project("image_viewer")

        code = '''
print("NOVA Image Viewer")
'''

        self.write("image_viewer/main.py", code)

        return "Image Viewer created."


    # ==========================================
    # VIDEO PLAYER
    # ==========================================

    def create_video_player(self):

        self.create_project("video_player")

        code = '''
print("NOVA Video Player")
'''

        self.write("video_player/main.py", code)

        return "Video Player created."


    # ==========================================
    # MUSIC PLAYER
    # ==========================================

    def create_music_player(self):

        self.create_project("music_player")

        code = '''
print("NOVA Music Player")
'''

        self.write("music_player/main.py", code)

        return "Music Player created."


    # ==========================================
    # PAINT APP
    # ==========================================

    def create_paint(self):

        self.create_project("paint_app")

        code = '''
print("NOVA Paint")
'''

        self.write("paint_app/main.py", code)

        return "Paint App created."


    # ==========================================
    # TERMINAL
    # ==========================================

    def create_terminal(self):

        self.create_project("terminal_app")

        code = '''
print("NOVA Terminal")
'''

        self.write("terminal_app/main.py", code)

        return "Terminal App created."


    # ==========================================
    # CLOCK
    # ==========================================

    def create_clock(self):

        self.create_project("clock_app")

        code = '''
import time

while True:

    print(time.strftime("%H:%M:%S"))

    time.sleep(1)
'''

        self.write("clock_app/main.py", code)

        return "Clock App created."
