"""
NOVA Desktop Generator
Creates Tkinter desktop applications.
"""

import os

PROJECTS = os.path.expanduser("~/NOVA/generated_projects")

os.makedirs(PROJECTS, exist_ok=True)


def create_desktop_app(name):

    folder = os.path.join(
        PROJECTS,
        name.replace(" ", "_").lower()
    )

    os.makedirs(folder, exist_ok=True)

    code = '''import tkinter as tk

window = tk.Tk()

window.title("NOVA Desktop App")
window.geometry("500x300")

label = tk.Label(
    window,
    text="Welcome to your NOVA Desktop App",
    font=("Arial",16)
)

label.pack(pady=20)

button = tk.Button(
    window,
    text="Click Me",
    command=lambda: label.config(text="Button Clicked!")
)

button.pack()

window.mainloop()
'''

    readme = f'''# {name}

Generated by NOVA

Run:

python main.py
'''

    with open(os.path.join(folder, "main.py"), "w") as f:
        f.write(code)

    with open(os.path.join(folder, "README.md"), "w") as f:
        f.write(readme)

    return f"Desktop app '{name}' created successfully in {folder}"


def calculator():
    return create_desktop_app("Desktop Calculator")


def notes():
    return create_desktop_app("Desktop Notes")


def music_player():
    return create_desktop_app("Desktop Music Player")


def file_manager():
    return create_desktop_app("Desktop File Manager")
