import os


class DjangoBuilder:

    def write(self, filename, code):

        with open(filename, "w", encoding="utf-8") as f:
            f.write(code)


    def create_project(self, name):

        os.makedirs(name, exist_ok=True)
        os.makedirs(f"{name}/templates", exist_ok=True)
        os.makedirs(f"{name}/static", exist_ok=True)

        manage = '''#!/usr/bin/env python

print("Run these commands:")

print("django-admin startproject project .")

print("python manage.py runserver")
'''

        views = '''from django.http import HttpResponse

def home(request):

    return HttpResponse("<h1>Welcome to NOVA Django</h1>")
'''

        urls = '''from django.urls import path

from . import views

urlpatterns = [

    path("", views.home),

]
'''

        html = '''<!DOCTYPE html>

<html>

<head>

<title>Django Website</title>

</head>

<body>

<h1>Website Generated by NOVA</h1>

<p>Edit this page to build your project.</p>

</body>

</html>
'''

        css = '''body{

font-family:Arial;

background:#202020;

color:white;

text-align:center;

}
'''

        requirements = '''Django
'''

        readme = f'''# {name}

Generated by NOVA

Install:

pip install -r requirements.txt

Create project:

django-admin startproject project .

Run:

python manage.py runserver
'''

        self.write(f"{name}/manage.py", manage)
        self.write(f"{name}/views.py", views)
        self.write(f"{name}/urls.py", urls)
        self.write(f"{name}/templates/index.html", html)
        self.write(f"{name}/static/style.css", css)
        self.write(f"{name}/requirements.txt", requirements)
        self.write(f"{name}/README.md", readme)

        return f"Django project '{name}' created."


    def create_blog(self):
        return self.create_project("django_blog")


    def create_school(self):
        return self.create_project("django_school")


    def create_store(self):
        return self.create_project("django_store")


    def create_dashboard(self):
        return self.create_project("django_dashboard")


    def create_portfolio(self):
        return self.create_project("django_portfolio")
