import os


class DockerBuilder:

    def write(self, filename, code):

        with open(filename, "w", encoding="utf-8") as f:
            f.write(code)


    def create_project(self, name):

        os.makedirs(name, exist_ok=True)

        readme = f"""# {name}

Generated by NOVA

Docker project template.
"""

        self.write(f"{name}/README.md", readme)

        return f"{name} created."


    # ==========================================
    # PYTHON DOCKER
    # ==========================================

    def create_python_container(self):

        self.create_project("python_docker")

        dockerfile = '''FROM python:3.12

WORKDIR /app

COPY . .

CMD ["python","main.py"]
'''

        main = '''print("Python Docker Container Running")
'''

        self.write("python_docker/Dockerfile", dockerfile)
        self.write("python_docker/main.py", main)

        return "Python Docker project created."


    # ==========================================
    # FLASK DOCKER
    # ==========================================

    def create_flask_container(self):

        self.create_project("flask_docker")

        dockerfile = '''FROM python:3.12

WORKDIR /app

COPY . .

RUN pip install flask

CMD ["python","app.py"]
'''

        app = '''
from flask import Flask

app = Flask(__name__)

@app.route("/")
def home():

    return "NOVA Flask Docker"

app.run(host="0.0.0.0", port=5000)
'''

        self.write("flask_docker/Dockerfile", dockerfile)
        self.write("flask_docker/app.py", app)

        return "Flask Docker project created."


    # ==========================================
    # FASTAPI DOCKER
    # ==========================================

    def create_fastapi_container(self):

        self.create_project("fastapi_docker")

        dockerfile = '''FROM python:3.12

WORKDIR /app

COPY . .

RUN pip install fastapi uvicorn

CMD ["uvicorn","main:app","--host","0.0.0.0","--port","8000"]
'''

        main = '''
from fastapi import FastAPI

app = FastAPI()

@app.get("/")
def home():

    return {"message":"NOVA FastAPI"}
'''

        self.write("fastapi_docker/Dockerfile", dockerfile)
        self.write("fastapi_docker/main.py", main)

        return "FastAPI Docker project created."


    # ==========================================
    # NODE DOCKER
    # ==========================================

    def create_node_container(self):

        self.create_project("node_docker")

        dockerfile = '''FROM node:20

WORKDIR /app

COPY . .

CMD ["node","server.js"]
'''

        server = '''
console.log("NOVA Node Docker");
'''

        self.write("node_docker/Dockerfile", dockerfile)
        self.write("node_docker/server.js", server)

        return "Node Docker project created."


    # ==========================================
    # REACT DOCKER
    # ==========================================

    def create_react_container(self):

        self.create_project("react_docker")

        dockerfile = '''FROM node:20

WORKDIR /app

COPY . .

CMD ["npm","start"]
'''

        self.write("react_docker/Dockerfile", dockerfile)

        return "React Docker project created."


    # ==========================================
    # MYSQL DOCKER
    # ==========================================

    def create_mysql_container(self):

        self.create_project("mysql_docker")

        dockerfile = '''FROM mysql:8
'''

        self.write("mysql_docker/Dockerfile", dockerfile)

        return "MySQL Docker project created."


    # ==========================================
    # POSTGRES DOCKER
    # ==========================================

    def create_postgres_container(self):

        self.create_project("postgres_docker")

        dockerfile = '''FROM postgres:16
'''

        self.write("postgres_docker/Dockerfile", dockerfile)

        return "PostgreSQL Docker project created."


    # ==========================================
    # REDIS DOCKER
    # ==========================================

    def create_redis_container(self):

        self.create_project("redis_docker")

        dockerfile = '''FROM redis:latest
'''

        self.write("redis_docker/Dockerfile", dockerfile)

        return "Redis Docker project created."


    # ==========================================
    # NGINX DOCKER
    # ==========================================

    def create_nginx_container(self):

        self.create_project("nginx_docker")

        dockerfile = '''FROM nginx:latest
'''

        self.write("nginx_docker/Dockerfile", dockerfile)

        return "Nginx Docker project created."


    # ==========================================
    # DOCKER COMPOSE
    # ==========================================

    def create_compose(self):

        self.create_project("docker_compose")

        compose = '''
version: "3"

services:

  app:

    image: python:3.12

    container_name: NOVA
'''

        self.write("docker_compose/docker-compose.yml", compose)

        return "Docker Compose project created."
