"""
NOVA Flask Website Generator
"""

import os

PROJECTS = os.path.expanduser("~/NOVA/generated_projects")


def create_flask_project(name):

    folder = os.path.join(
        PROJECTS,
        name.replace(" ", "_").lower()
    )

    os.makedirs(folder, exist_ok=True)
    os.makedirs(os.path.join(folder, "templates"), exist_ok=True)
    os.makedirs(os.path.join(folder, "static"), exist_ok=True)

    app = """from flask import Flask, render_template

app = Flask(__name__)

@app.route("/")
def home():
    return render_template("index.html")

if __name__ == "__main__":
    app.run(debug=True)
"""

    html = """<!DOCTYPE html>
<html>

<head>
    <title>NOVA Website</title>
    <link rel="stylesheet" href="/static/style.css">
</head>

<body>

<h1>Welcome to NOVA</h1>

<p>Your website is ready.</p>

</body>

</html>
"""

    css = """body{

    font-family:Arial;

    background:#202020;

    color:white;

    text-align:center;

    padding-top:80px;

}
"""

    requirements = """Flask
"""

    readme = f"""# {name}

Generated by NOVA

Run:

pip install -r requirements.txt

python app.py
"""

    with open(os.path.join(folder, "app.py"), "w") as f:
        f.write(app)

    with open(os.path.join(folder, "templates", "index.html"), "w") as f:
        f.write(html)

    with open(os.path.join(folder, "static", "style.css"), "w") as f:
        f.write(css)

    with open(os.path.join(folder, "requirements.txt"), "w") as f:
        f.write(requirements)

    with open(os.path.join(folder, "README.md"), "w") as f:
        f.write(readme)

    return f"{name} website created successfully in {folder}"


flask_generator = create_flask_project
