import os


class FlaskBuilder:

    def write(self, filename, code):

        with open(filename, "w", encoding="utf-8") as f:
            f.write(code)


    def create_project(self, name):

        os.makedirs(name, exist_ok=True)
        os.makedirs(f"{name}/templates", exist_ok=True)
        os.makedirs(f"{name}/static", exist_ok=True)

        app = '''from flask import Flask, render_template

app = Flask(__name__)

@app.route("/")
def home():
    return render_template("index.html")

@app.route("/about")
def about():
    return "<h1>About Page</h1>"

@app.route("/contact")
def contact():
    return "<h1>Contact Page</h1>"

if __name__ == "__main__":
    app.run(debug=True)
'''

        html = '''<!DOCTYPE html>
<html>

<head>

<title>Flask Website</title>

<link rel="stylesheet" href="/static/style.css">

</head>

<body>

<h1>Welcome to your Flask Website</h1>

<p>Generated by NOVA.</p>

</body>

</html>
'''

        css = '''body{

font-family:Arial;

background:#101820;

color:white;

text-align:center;

padding:40px;

}

h1{

color:#00ccff;

}
'''

        requirements = '''Flask
'''

        readme = f'''# {name}

Generated by NOVA

Run:

pip install -r requirements.txt

python app.py
'''

        self.write(f"{name}/app.py", app)
        self.write(f"{name}/templates/index.html", html)
        self.write(f"{name}/static/style.css", css)
        self.write(f"{name}/requirements.txt", requirements)
        self.write(f"{name}/README.md", readme)

        return f"Flask project '{name}' created."


    def create_blog(self):
        return self.create_project("flask_blog")


    def create_portfolio(self):
        return self.create_project("flask_portfolio")


    def create_shop(self):
        return self.create_project("flask_shop")


    def create_dashboard(self):
        return self.create_project("flask_dashboard")
