import os


class GameBuilder:

    def write(self, filename, code):

        with open(filename, "w", encoding="utf-8") as f:
            f.write(code)


    def create_project(self, name):

        os.makedirs(name, exist_ok=True)

        readme = f"""# {name}

Generated by NOVA

Run:

python main.py
"""

        main = """print("Welcome to your NOVA Game")
"""

        self.write(f"{name}/README.md", readme)
        self.write(f"{name}/main.py", main)

        return f"{name} created."


    # ----------------------------
    # Snake
    # ----------------------------

    def create_snake(self):

        return self.create_project("snake_game")


    # ----------------------------
    # Tic Tac Toe
    # ----------------------------

    def create_tictactoe(self):

        return self.create_project("tic_tac_toe")


    # ----------------------------
    # Pong
    # ----------------------------

    def create_pong(self):

        return self.create_project("pong_game")


    # ----------------------------
    # Flappy Bird
    # ----------------------------

    def create_flappy(self):

        return self.create_project("flappy_bird")


    # ----------------------------
    # Space Shooter
    # ----------------------------

    def create_space(self):

        return self.create_project("space_shooter")


    # ----------------------------
    # Platform Game
    # ----------------------------

    def create_platform(self):

        return self.create_project("platform_game")


    # ----------------------------
    # Racing
    # ----------------------------

    def create_racing(self):

        return self.create_project("racing_game")


    # ----------------------------
    # Chess
    # ----------------------------

    def create_chess(self):

        return self.create_project("chess_game")


    # ----------------------------
    # Checkers
    # ----------------------------

    def create_checkers(self):

        return self.create_project("checkers_game")


    # ----------------------------
    # Sudoku
    # ----------------------------

    def create_sudoku(self):

        return self.create_project("sudoku_game")


    # ----------------------------
    # Memory Game
    # ----------------------------

    def create_memory(self):

        return self.create_project("memory_game")


    # ----------------------------
    # Quiz Game
    # ----------------------------

    def create_quiz(self):

        return self.create_project("quiz_game")


    # ----------------------------
    # Card Game
    # ----------------------------

    def create_cards(self):

        return self.create_project("card_game")


    # ----------------------------
    # RPG
    # ----------------------------

    def create_rpg(self):

        return self.create_project("rpg_game")


    # ----------------------------
    # Adventure
    # ----------------------------

    def create_adventure(self):

        return self.create_project("adventure_game")


    # ----------------------------
    # Survival
    # ----------------------------

    def create_survival(self):

        return self.create_project("survival_game")


    # ----------------------------
    # Zombie
    # ----------------------------

    def create_zombie(self):

        return self.create_project("zombie_game")


    # ----------------------------
    # Football
    # ----------------------------

    def create_football(self):

        return self.create_project("football_game")


    # ----------------------------
    # Basketball
    # ----------------------------

    def create_basketball(self):

        return self.create_project("basketball_game")


    # ----------------------------
    # Multiplayer
    # ----------------------------

    def create_multiplayer(self):

        return self.create_project("multiplayer_game")
