import os


class GitBuilder:

    def write(self, filename, code):

        with open(filename, "w", encoding="utf-8") as f:
            f.write(code)


    def create_project(self, name):

        os.makedirs(name, exist_ok=True)

        readme = f"""# {name}

Generated by NOVA

Git project template.
"""

        self.write(f"{name}/README.md", readme)

        return f"{name} created."


    # ==========================================
    # GIT REPOSITORY
    # ==========================================

    def create_repository(self):

        self.create_project("git_repository")

        gitignore = """__pycache__/
*.pyc
.env
.venv/
node_modules/
build/
dist/
"""

        self.write("git_repository/.gitignore", gitignore)

        return "Git repository created."


    # ==========================================
    # PYTHON PROJECT
    # ==========================================

    def create_python_repo(self):

        self.create_project("python_repo")

        self.write(
            "python_repo/.gitignore",
            "__pycache__/\n*.pyc\n.venv/\n.env\n"
        )

        return "Python repository created."


    # ==========================================
    # NODE PROJECT
    # ==========================================

    def create_node_repo(self):

        self.create_project("node_repo")

        self.write(
            "node_repo/.gitignore",
            "node_modules/\n.env\nnpm-debug.log\n"
        )

        return "Node repository created."


    # ==========================================
    # FLASK PROJECT
    # ==========================================

    def create_flask_repo(self):

        self.create_project("flask_repo")

        self.write(
            "flask_repo/.gitignore",
            "__pycache__/\ninstance/\n.env\n"
        )

        return "Flask repository created."


    # ==========================================
    # DJANGO PROJECT
    # ==========================================

    def create_django_repo(self):

        self.create_project("django_repo")

        self.write(
            "django_repo/.gitignore",
            "__pycache__/\ndb.sqlite3\n.env\n"
        )

        return "Django repository created."


    # ==========================================
    # REACT PROJECT
    # ==========================================

    def create_react_repo(self):

        self.create_project("react_repo")

        self.write(
            "react_repo/.gitignore",
            "node_modules/\nbuild/\n.env\n"
        )

        return "React repository created."


    # ==========================================
    # LICENSE
    # ==========================================

    def create_license(self):

        self.create_project("license_project")

        mit = """MIT License

Copyright (c)

Permission is hereby granted...
"""

        self.write("license_project/LICENSE", mit)

        return "MIT License created."


    # ==========================================
    # CHANGELOG
    # ==========================================

    def create_changelog(self):

        self.create_project("changelog_project")

        changelog = """# Changelog

## Version 1.0.0

- Initial Release
"""

        self.write("changelog_project/CHANGELOG.md", changelog)

        return "Changelog created."


    # ==========================================
    # CONTRIBUTING
    # ==========================================

    def create_contributing(self):

        self.create_project("contributing_project")

        contributing = """# Contributing

1. Fork the project.
2. Create a branch.
3. Commit changes.
4. Open a Pull Request.
"""

        self.write(
            "contributing_project/CONTRIBUTING.md",
            contributing
        )

        return "Contributing guide created."


    # ==========================================
    # GITHUB ACTIONS
    # ==========================================

    def create_github_actions(self):

        os.makedirs(
            "github_actions/.github/workflows",
            exist_ok=True
        )

        workflow = """name: Python CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Setup Python

        uses: actions/setup-python@v5

      - run: python --version
"""

        self.write(
            "github_actions/.github/workflows/python.yml",
            workflow
        )

        return "GitHub Actions workflow created."
