import os
import json


class LearningBuilder:

    def write(self, filename, code):

        os.makedirs(os.path.dirname(filename), exist_ok=True)

        with open(filename, "w", encoding="utf-8") as f:
            f.write(code)


    def create_project(self, name):

        os.makedirs(name, exist_ok=True)

        self.write(
            f"{name}/README.md",
            f"# {name}\n\nGenerated by NOVA Learning Builder\n"
        )

        return f"{name} created."


    # =====================================
    # KNOWLEDGE BASE
    # =====================================

    def create_knowledge_base(self):

        self.create_project("knowledge_base")

        data = {
            "books": [],
            "websites": [],
            "notes": [],
            "documents": [],
            "skills": []
        }

        with open(
            "knowledge_base/data.json",
            "w",
            encoding="utf-8"
        ) as f:

            json.dump(data, f, indent=4)

        return "Knowledge Base created."


    # =====================================
    # NOTES
    # =====================================

    def create_notes(self):

        self.create_project("notes")

        self.write(
            "notes/main.py",
            'print("NOVA Notes System")'
        )

        return "Notes project created."


    # =====================================
    # FLASHCARDS
    # =====================================

    def create_flashcards(self):

        self.create_project("flashcards")

        self.write(
            "flashcards/main.py",
            'print("Flashcards Template")'
        )

        return "Flashcards created."


    # =====================================
    # QUIZ
    # =====================================

    def create_quiz(self):

        self.create_project("quiz_system")

        self.write(
            "quiz_system/main.py",
            'print("Quiz System")'
        )

        return "Quiz System created."


    # =====================================
    # PDF LIBRARY
    # =====================================

    def create_pdf_library(self):

        self.create_project("pdf_library")

        self.write(
            "pdf_library/main.py",
            'print("PDF Library")'
        )

        return "PDF Library created."


    # =====================================
    # BOOK LIBRARY
    # =====================================

    def create_book_library(self):

        self.create_project("book_library")

        self.write(
            "book_library/main.py",
            'print("Book Library")'
        )

        return "Book Library created."


    # =====================================
    # COURSE MANAGER
    # =====================================

    def create_courses(self):

        self.create_project("courses")

        self.write(
            "courses/main.py",
            'print("Course Manager")'
        )

        return "Courses project created."


    # =====================================
    # SKILL TRACKER
    # =====================================

    def create_skill_tracker(self):

        self.create_project("skill_tracker")

        self.write(
            "skill_tracker/main.py",
            'print("Skill Tracker")'
        )

        return "Skill Tracker created."


    # =====================================
    # DAILY LEARNING
    # =====================================

    def create_daily_learning(self):

        self.create_project("daily_learning")

        self.write(
            "daily_learning/main.py",
            'print("Daily Learning")'
        )

        return "Daily Learning created."


    # =====================================
    # STUDY PLANNER
    # =====================================

    def create_study_planner(self):

        self.create_project("study_planner")

        self.write(
            "study_planner/main.py",
            'print("Study Planner")'
        )

        return "Study Planner created."


    # =====================================
    # REVISION
    # =====================================

    def create_revision(self):

        self.create_project("revision")

        self.write(
            "revision/main.py",
            'print("Revision System")'
        )

        return "Revision System created."


    # =====================================
    # AI TUTOR
    # =====================================

    def create_ai_tutor(self):

        self.create_project("ai_tutor")

        self.write(
            "ai_tutor/main.py",
            'print("NOVA AI Tutor")'
        )

        return "AI Tutor created."
