import os


class MachineLearningBuilder:

    def write(self, filename, code):

        os.makedirs(os.path.dirname(filename), exist_ok=True)

        with open(filename, "w", encoding="utf-8") as f:
            f.write(code)


    def create_project(self, name):

        os.makedirs(name, exist_ok=True)

        self.write(
            f"{name}/README.md",
            f"# {name}\n\nGenerated by NOVA\n"
        )

        return f"{name} created."


    # ==========================================
    # LINEAR REGRESSION
    # ==========================================

    def create_linear_regression(self):

        self.create_project("linear_regression")

        code = '''
from sklearn.linear_model import LinearRegression

print("Linear Regression Template")
'''

        self.write("linear_regression/main.py", code)

        return "Linear Regression project created."


    # ==========================================
    # LOGISTIC REGRESSION
    # ==========================================

    def create_logistic_regression(self):

        self.create_project("logistic_regression")

        code = '''
from sklearn.linear_model import LogisticRegression

print("Logistic Regression Template")
'''

        self.write("logistic_regression/main.py", code)

        return "Logistic Regression project created."


    # ==========================================
    # DECISION TREE
    # ==========================================

    def create_decision_tree(self):

        self.create_project("decision_tree")

        code = '''
from sklearn.tree import DecisionTreeClassifier

print("Decision Tree Template")
'''

        self.write("decision_tree/main.py", code)

        return "Decision Tree project created."


    # ==========================================
    # RANDOM FOREST
    # ==========================================

    def create_random_forest(self):

        self.create_project("random_forest")

        code = '''
from sklearn.ensemble import RandomForestClassifier

print("Random Forest Template")
'''

        self.write("random_forest/main.py", code)

        return "Random Forest project created."


    # ==========================================
    # K-MEANS
    # ==========================================

    def create_kmeans(self):

        self.create_project("kmeans")

        code = '''
from sklearn.cluster import KMeans

print("K-Means Clustering Template")
'''

        self.write("kmeans/main.py", code)

        return "K-Means project created."


    # ==========================================
    # KNN
    # ==========================================

    def create_knn(self):

        self.create_project("knn_classifier")

        code = '''
from sklearn.neighbors import KNeighborsClassifier

print("KNN Template")
'''

        self.write("knn_classifier/main.py", code)

        return "KNN project created."


    # ==========================================
    # SVM
    # ==========================================

    def create_svm(self):

        self.create_project("svm_classifier")

        code = '''
from sklearn.svm import SVC

print("Support Vector Machine Template")
'''

        self.write("svm_classifier/main.py", code)

        return "SVM project created."


    # ==========================================
    # NAIVE BAYES
    # ==========================================

    def create_naive_bayes(self):

        self.create_project("naive_bayes")

        code = '''
from sklearn.naive_bayes import GaussianNB

print("Naive Bayes Template")
'''

        self.write("naive_bayes/main.py", code)

        return "Naive Bayes project created."


    # ==========================================
    # RECOMMENDATION SYSTEM
    # ==========================================

    def create_recommender(self):

        self.create_project("recommendation_system")

        code = '''
print("Recommendation System Template")
'''

        self.write("recommendation_system/main.py", code)

        return "Recommendation System created."


    # ==========================================
    # MODEL TRAINER
    # ==========================================

    def create_model_trainer(self):

        self.create_project("model_trainer")

        code = '''
print("Machine Learning Model Trainer")
'''

        self.write("model_trainer/main.py", code)

        return "Model Trainer created."
