"""
NOVA Machine Learning Generator
"""

import os

PROJECTS = os.path.expanduser("~/NOVA/generated_projects")

os.makedirs(PROJECTS, exist_ok=True)


def create_ml_project(name):

    folder = os.path.join(
        PROJECTS,
        name.replace(" ", "_").lower()
    )

    os.makedirs(folder, exist_ok=True)

    main = '''"""
Machine Learning Project
Generated by NOVA
"""

from sklearn.linear_model import LinearRegression
import numpy as np

X = np.array([[1],[2],[3],[4],[5]])
y = np.array([2,4,6,8,10])

model = LinearRegression()
model.fit(X, y)

prediction = model.predict([[6]])

print("Prediction:", prediction[0])
'''

    requirements = '''numpy
scikit-learn
'''

    readme = f'''# {name}

Generated by NOVA

Install:

pip install -r requirements.txt

Run:

python main.py
'''

    with open(os.path.join(folder, "main.py"), "w") as f:
        f.write(main)

    with open(os.path.join(folder, "requirements.txt"), "w") as f:
        f.write(requirements)

    with open(os.path.join(folder, "README.md"), "w") as f:
        f.write(readme)

    return f"Machine Learning project '{name}' created successfully in {folder}"


def prediction_model():
    return create_ml_project("Prediction Model")


def image_classifier():
    return create_ml_project("Image Classifier")


def text_classifier():
    return create_ml_project("Text Classifier")


def recommendation_system():
    return create_ml_project("Recommendation System")


def chatbot_model():
    return create_ml_project("Chatbot Model")
