import os


class MobileBuilder:

    def write(self, filename, code):

        with open(filename, "w", encoding="utf-8") as f:
            f.write(code)

    def create_project(self, name):

        os.makedirs(name, exist_ok=True)

        readme = f"""# {name}

Mobile project generated by NOVA.

"""

        self.write(f"{name}/README.md", readme)

        return f"{name} created."


    # ==========================================
    # FLUTTER APP
    # ==========================================

    def create_flutter(self):

        self.create_project("flutter_app")

        code = '''
import 'package:flutter/material.dart';

void main(){

  runApp(const MyApp());

}

class MyApp extends StatelessWidget{

  const MyApp({super.key});

  @override

  Widget build(BuildContext context){

    return MaterialApp(

      home: Scaffold(

        appBar: AppBar(

          title: const Text("NOVA Flutter"),

        ),

        body: const Center(

          child: Text("Hello World"),

        ),

      ),

    );

  }

}
'''

        self.write("flutter_app/main.dart", code)

        return "Flutter project created."


    # ==========================================
    # REACT NATIVE
    # ==========================================

    def create_react_native(self):

        self.create_project("react_native")

        code = '''
import React from "react";

import {View,Text} from "react-native";

export default function App(){

    return(

        <View>

            <Text>

                Welcome to NOVA

            </Text>

        </View>

    );

}
'''

        self.write("react_native/App.js", code)

        return "React Native project created."


    # ==========================================
    # KOTLIN APP
    # ==========================================

    def create_kotlin(self):

        self.create_project("kotlin_app")

        code = '''
fun main(){

    println("Welcome to NOVA Kotlin")

}
'''

        self.write("kotlin_app/Main.kt", code)

        return "Kotlin project created."


    # ==========================================
    # JAVA APP
    # ==========================================

    def create_java(self):

        self.create_project("java_app")

        code = '''
public class Main{

    public static void main(String[] args){

        System.out.println("Welcome to NOVA Java");

    }

}
'''

        self.write("java_app/Main.java", code)

        return "Java mobile project created."


    # ==========================================
    # NOTES APP
    # ==========================================

    def create_notes(self):

        return self.create_project("mobile_notes")


    # ==========================================
    # CHAT APP
    # ==========================================

    def create_chat(self):

        return self.create_project("mobile_chat")


    # ==========================================
    # MUSIC PLAYER
    # ==========================================

    def create_music(self):

        return self.create_project("mobile_music")


    # ==========================================
    # VIDEO PLAYER
    # ==========================================

    def create_video(self):

        return self.create_project("mobile_video")


    # ==========================================
    # SHOPPING APP
    # ==========================================

    def create_store(self):

        return self.create_project("mobile_store")


    # ==========================================
    # BANKING APP
    # ==========================================

    def create_bank(self):

        return self.create_project("mobile_bank")


    # ==========================================
    # SOCIAL MEDIA APP
    # ==========================================

    def create_social(self):

        return self.create_project("mobile_social")


    # ==========================================
    # AI ASSISTANT
    # ==========================================

    def create_ai(self):

        return self.create_project("mobile_ai")


    # ==========================================
    # TRADING APP
    # ==========================================

    def create_trading(self):

        return self.create_project("mobile_trading")


    # ==========================================
    # E-LEARNING APP
    # ==========================================

    def create_learning(self):

        return self.create_project("mobile_learning")


    # ==========================================
    # HEALTH APP
    # ==========================================

    def create_health(self):

        return self.create_project("mobile_health")
