import os


class NLPBuilder:

    def write(self, filename, code):

        os.makedirs(os.path.dirname(filename), exist_ok=True)

        with open(filename, "w", encoding="utf-8") as f:
            f.write(code)


    def create_project(self, name):

        os.makedirs(name, exist_ok=True)

        self.write(
            f"{name}/README.md",
            f"# {name}\n\nGenerated by NOVA\n"
        )

        return f"{name} created."


    # ==========================================
    # CHATBOT
    # ==========================================

    def create_chatbot(self):

        self.create_project("chatbot")

        code = '''
print("NOVA NLP Chatbot")
'''

        self.write("chatbot/main.py", code)

        return "Chatbot created."


    # ==========================================
    # TRANSLATOR
    # ==========================================

    def create_translator(self):

        self.create_project("translator")

        code = '''
print("Language Translator Template")
'''

        self.write("translator/main.py", code)

        return "Translator created."


    # ==========================================
    # SUMMARIZER
    # ==========================================

    def create_summarizer(self):

        self.create_project("summarizer")

        code = '''
text = input("Enter text: ")

print(text[:200])
'''

        self.write("summarizer/main.py", code)

        return "Summarizer created."


    # ==========================================
    # SENTIMENT ANALYSIS
    # ==========================================

    def create_sentiment(self):

        self.create_project("sentiment_analysis")

        code = '''
print("Sentiment Analysis Template")
'''

        self.write("sentiment_analysis/main.py", code)

        return "Sentiment Analysis created."


    # ==========================================
    # QUESTION ANSWERING
    # ==========================================

    def create_question_answering(self):

        self.create_project("question_answering")

        code = '''
print("Question Answering Template")
'''

        self.write("question_answering/main.py", code)

        return "Question Answering created."


    # ==========================================
    # TEXT CLASSIFICATION
    # ==========================================

    def create_text_classifier(self):

        self.create_project("text_classifier")

        code = '''
print("Text Classification Template")
'''

        self.write("text_classifier/main.py", code)

        return "Text Classifier created."


    # ==========================================
    # SPELL CHECKER
    # ==========================================

    def create_spell_checker(self):

        self.create_project("spell_checker")

        code = '''
print("Spell Checker Template")
'''

        self.write("spell_checker/main.py", code)

        return "Spell Checker created."


    # ==========================================
    # KEYWORD EXTRACTION
    # ==========================================

    def create_keyword_extractor(self):

        self.create_project("keyword_extractor")

        code = '''
print("Keyword Extraction Template")
'''

        self.write("keyword_extractor/main.py", code)

        return "Keyword Extractor created."


    # ==========================================
    # TEXT GENERATOR
    # ==========================================

    def create_text_generator(self):

        self.create_project("text_generator")

        code = '''
print("Text Generator Template")
'''

        self.write("text_generator/main.py", code)

        return "Text Generator created."


    # ==========================================
    # SPEECH COMMANDS
    # ==========================================

    def create_speech_commands(self):

        self.create_project("speech_commands")

        code = '''
print("Speech Commands Template")
'''

        self.write("speech_commands/main.py", code)

        return "Speech Commands created."


    # ==========================================
    # VOICE CHATBOT
    # ==========================================

    def create_voice_chatbot(self):

        self.create_project("voice_chatbot")

        code = '''
print("Voice Chatbot Template")
'''

        self.write("voice_chatbot/main.py", code)

        return "Voice Chatbot created."


    # ==========================================
    # LANGUAGE DETECTOR
    # ==========================================

    def create_language_detector(self):

        self.create_project("language_detector")

        code = '''
print("Language Detection Template")
'''

        self.write("language_detector/main.py", code)

        return "Language Detector created."
