import os


class NodeBuilder:

    def write(self, filename, code):

        with open(filename, "w", encoding="utf-8") as f:
            f.write(code)


    def create_project(self, name):

        os.makedirs(name, exist_ok=True)

        package = '''{
  "name":"NOVA-node",
  "version":"1.0.0",
  "main":"server.js",
  "scripts":{
    "start":"node server.js"
  }
}
'''

        server = '''const http = require("http");

const server = http.createServer((req,res)=>{

    res.writeHead(200,{"Content-Type":"text/html"});

    res.end("<h1>Welcome to NOVA Node.js Server</h1>");

});

server.listen(3000,()=>{

    console.log("Server running on port 3000");

});
'''

        readme = f'''# {name}

Generated by NOVA

Run:

npm install

npm start
'''

        gitignore = '''node_modules/
.env
'''

        self.write(f"{name}/package.json", package)
        self.write(f"{name}/server.js", server)
        self.write(f"{name}/README.md", readme)
        self.write(f"{name}/.gitignore", gitignore)

        return f"Node.js project '{name}' created."


    def create_api(self):

        return self.create_project("node_api")


    def create_chat(self):

        return self.create_project("node_chat")


    def create_blog(self):

        return self.create_project("node_blog")


    def create_dashboard(self):

        return self.create_project("node_dashboard")


    def create_store(self):

        return self.create_project("node_store")


    def create_school(self):

        return self.create_project("node_school")


    def create_music(self):

        return self.create_project("node_music")


    def create_video(self):

        return self.create_project("node_video")


    def create_trading(self):

        return self.create_project("node_trading")


    def create_ai(self):

        return self.create_project("node_ai")
