import os


class OperatingSystemBuilder:

    def write(self, filename, code):

        os.makedirs(os.path.dirname(filename), exist_ok=True)

        with open(filename, "w", encoding="utf-8") as f:
            f.write(code)


    def create_project(self, name):

        os.makedirs(name, exist_ok=True)

        self.write(
            f"{name}/README.md",
            f"# {name}\n\nGenerated by NOVA Operating System Builder\n"
        )

        return f"{name} created."


    # ==========================================
    # SHELL
    # ==========================================

    def create_shell(self):

        self.create_project("shell")

        code = '''
print("NOVA Shell")

while True:

    command = input("NOVA> ")

    if command == "exit":
        break

    print("You entered:", command)
'''

        self.write("shell/main.py", code)

        return "Shell project created."


    # ==========================================
    # FILE MANAGER
    # ==========================================

    def create_file_manager(self):

        self.create_project("file_manager")

        code = '''
import os

print(os.listdir("."))
'''

        self.write("file_manager/main.py", code)

        return "File Manager created."


    # ==========================================
    # PROCESS MANAGER
    # ==========================================

    def create_process_manager(self):

        self.create_project("process_manager")

        code = '''
print("Process Manager Template")
'''

        self.write("process_manager/main.py", code)

        return "Process Manager created."


    # ==========================================
    # TASK MANAGER
    # ==========================================

    def create_task_manager(self):

        self.create_project("task_manager")

        code = '''
print("Task Manager Template")
'''

        self.write("task_manager/main.py", code)

        return "Task Manager created."


    # ==========================================
    # TERMINAL
    # ==========================================

    def create_terminal(self):

        self.create_project("terminal")

        code = '''
print("NOVA Terminal")
'''

        self.write("terminal/main.py", code)

        return "Terminal created."


    # ==========================================
    # PACKAGE MANAGER
    # ==========================================

    def create_package_manager(self):

        self.create_project("package_manager")

        code = '''
print("Package Manager Template")
'''

        self.write("package_manager/main.py", code)

        return "Package Manager created."


    # ==========================================
    # SYSTEM MONITOR
    # ==========================================

    def create_system_monitor(self):

        self.create_project("system_monitor")

        code = '''
print("System Monitor Template")
'''

        self.write("system_monitor/main.py", code)

        return "System Monitor created."


    # ==========================================
    # BOOTLOADER
    # ==========================================

    def create_bootloader(self):

        self.create_project("bootloader")

        code = '''
print("Bootloader Template")
'''

        self.write("bootloader/main.py", code)

        return "Bootloader created."


    # ==========================================
    # KERNEL
    # ==========================================

    def create_kernel(self):

        self.create_project("kernel")

        code = '''
print("Educational Kernel Template")
'''

        self.write("kernel/main.py", code)

        return "Kernel project created."


    # ==========================================
    # OPERATING SYSTEM
    # ==========================================

    def create_operating_system(self):

        self.create_project("operating_system")

        code = '''
print("NOVA Operating System Project")
'''

        self.write("operating_system/main.py", code)

        return "Operating System project created."
