import os


class PackageBuilder:

    def write(self, filename, text):

        folder = os.path.dirname(filename)

        if folder:

            os.makedirs(folder, exist_ok=True)

        with open(filename, "w", encoding="utf-8") as f:

            f.write(text)


    def create_package(self, name):

        os.makedirs(name, exist_ok=True)

        self.write(

            f"{name}/__init__.py",

            f'""" {name} package """\n'

        )

        self.write(

            f"{name}/main.py",

            '''
def main():

    print("NOVA Package")

if __name__ == "__main__":

    main()
'''

        )

        self.write(

            f"{name}/README.md",

            f"# {name}\nGenerated by NOVA\n"

        )

        return f"{name} package created."


    def create_library(self, name):

        os.makedirs(name, exist_ok=True)

        self.write(

            f"{name}/__init__.py",

            ""

        )

        self.write(

            f"{name}/utils.py",

            '''
def hello():

    return "Hello from NOVA"
'''

        )

        return f"{name} library created."


    def create_cli(self, name):

        os.makedirs(name, exist_ok=True)

        self.write(

            f"{name}/cli.py",

            '''
def main():

    print("NOVA CLI Tool")

if __name__ == "__main__":

    main()
'''

        )

        return f"{name} CLI created."


    def create_config(self, name):

        self.write(

            f"{name}/config.py",

            '''
APP_NAME = "NOVA"

VERSION = "1.0.0"
'''

        )

        return "Config created."


    def create_requirements(self, name):

        self.write(

            f"{name}/requirements.txt",

            ""

        )

        return "requirements.txt created."


    def create_setup(self, name):

        self.write(

            f"{name}/setup.py",

            '''
from setuptools import setup

setup(

    name="NOVA",

    version="1.0.0",

    packages=["."]
)
'''

        )

        return "setup.py created."


    def create_license(self, name):

        self.write(

            f"{name}/LICENSE",

            "MIT License"

        )

        return "LICENSE created."


    def create_gitignore(self, name):

        self.write(

            f"{name}/.gitignore",

            '''
__pycache__/

*.pyc

.env

venv/
'''

        )

        return ".gitignore created."


    def create_tests(self, name):

        os.makedirs(f"{name}/tests", exist_ok=True)

        self.write(

            f"{name}/tests/test_main.py",

            '''
def test_example():

    assert True
'''

        )

        return "Tests created."


    def create_docs(self, name):

        os.makedirs(f"{name}/docs", exist_ok=True)

        self.write(

            f"{name}/docs/index.md",

            "# Documentation"

        )

        return "Documentation created."
