import os


class ProjectGenerator:

    def __init__(self):
        pass

    def create_folder(self, path):
        os.makedirs(path, exist_ok=True)

    def write(self, filename, text):

        folder = os.path.dirname(filename)

        if folder:
            os.makedirs(folder, exist_ok=True)

        with open(filename, "w", encoding="utf-8") as f:
            f.write(text)

    # ======================================
    # PYTHON PROJECT
    # ======================================

    def create_python_project(self, name):

        self.create_folder(name)

        self.write(
            f"{name}/main.py",
            'print("Hello from NOVA")\n'
        )

        self.write(
            f"{name}/README.md",
            f"# {name}\nGenerated by NOVA\n"
        )

        self.write(
            f"{name}/requirements.txt",
            ""
        )

        return f"{name} created."

    # ======================================
    # WEBSITE
    # ======================================

    def create_website(self, name):

        self.create_folder(name)

        self.write(
            f"{name}/index.html",
            "<h1>NOVA Website</h1>"
        )

        self.write(
            f"{name}/style.css",
            "body{font-family:Arial;}"
        )

        self.write(
            f"{name}/script.js",
            'console.log("NOVA");'
        )

        return f"{name} website created."

    # ======================================
    # FLASK
    # ======================================

    def create_flask(self, name):

        self.create_folder(name)

        self.write(
            f"{name}/app.py",
            '''
from flask import Flask

app = Flask(__name__)

@app.route("/")
def home():
    return "NOVA Flask App"

if __name__ == "__main__":
    app.run()
'''
        )

        self.write(
            f"{name}/requirements.txt",
            "flask\n"
        )

        return f"{name} Flask project created."

    # ======================================
    # FASTAPI
    # ======================================

    def create_fastapi(self, name):

        self.create_folder(name)

        self.write(
            f"{name}/main.py",
            '''
from fastapi import FastAPI

app = FastAPI()

@app.get("/")
def home():
    return {"message":"NOVA"}
'''
        )

        return f"{name} FastAPI project created."

    # ======================================
    # API PROJECT
    # ======================================

    def create_api(self, name):

        self.create_folder(name)

        self.write(
            f"{name}/api.py",
            '''
print("NOVA API")
'''
        )

        return f"{name} API created."

    # ======================================
    # AI PROJECT
    # ======================================

    def create_ai(self, name):

        self.create_folder(name)

        self.write(
            f"{name}/main.py",
            '''
print("NOVA AI Project")
'''
        )

        return f"{name} AI project created."

    # ======================================
    # GAME
    # ======================================

    def create_game(self, name):

        self.create_folder(name)

        self.write(
            f"{name}/game.py",
            '''
print("NOVA Game")
'''
        )

        return f"{name} Game created."

    # ======================================
    # MOBILE APP
    # ======================================

    def create_mobile(self, name):

        self.create_folder(name)

        self.write(
            f"{name}/README.md",
            "# Mobile App"
        )

        return f"{name} Mobile App created."

    # ======================================
    # DESKTOP APP
    # ======================================

    def create_desktop(self, name):

        self.create_folder(name)

        self.write(
            f"{name}/main.py",
            '''
print("Desktop App")
'''
        )

        return f"{name} Desktop App created."

    # ======================================
    # DATABASE
    # ======================================

    def create_database(self, name):

        self.create_folder(name)

        self.write(
            f"{name}/database.py",
            '''
import sqlite3

print("Database Ready")
'''
        )

        return f"{name} Database project created."

    # ======================================
    # FULL STACK
    # ======================================

    def create_full_stack(self, name):

        self.create_folder(name)

        folders = [

            "frontend",

            "backend",

            "database",

            "docs",

            "tests",

            "assets"

        ]

        for folder in folders:

            self.create_folder(f"{name}/{folder}")

        self.write(
            f"{name}/README.md",
            f"# {name}\nGenerated by NOVA\n"
        )

        return f"{name} Full Stack project created."
