"""
NOVA Pygame Generator
"""

import os

PROJECTS = os.path.expanduser("~/NOVA/generated_projects")


def create_game(name):

    folder = os.path.join(
        PROJECTS,
        name.replace(" ", "_").lower()
    )

    os.makedirs(folder, exist_ok=True)

    folders = [
        "assets",
        "images",
        "sounds",
        "levels"
    ]

    for item in folders:
        os.makedirs(
            os.path.join(folder, item),
            exist_ok=True
        )

    main = """import pygame
import sys

pygame.init()

WIDTH = 800
HEIGHT = 600

screen = pygame.display.set_mode((WIDTH, HEIGHT))
pygame.display.set_caption("NOVA Game")

clock = pygame.time.Clock()

running = True

while running:

    for event in pygame.event.get():

        if event.type == pygame.QUIT:
            running = False

    screen.fill((30,30,30))

    pygame.display.flip()

    clock.tick(60)

pygame.quit()
sys.exit()
"""

    requirements = """pygame
"""

    readme = f"""# {name}

Generated by NOVA

Install:

pip install -r requirements.txt

Run:

python main.py
"""

    with open(os.path.join(folder, "main.py"), "w") as f:
        f.write(main)

    with open(os.path.join(folder, "requirements.txt"), "w") as f:
        f.write(requirements)

    with open(os.path.join(folder, "README.md"), "w") as f:
        f.write(readme)

    return f"{name} game created successfully in {folder}"


pygame_generator = create_game
