import os
import random
import string


class PythonBuilder:

    def __init__(self):
        pass

    def write_file(self, filename, code):
        with open(filename, "w", encoding="utf-8") as f:
            f.write(code)

        return f"{filename} created."

    # ==========================================
    # BASIC PYTHON PROGRAM
    # ==========================================

    def create_program(self, name):

        code = f'''"""
{name}.py
Generated by NOVA
"""

def main():

    print("Welcome to {name}")

if __name__ == "__main__":

    main()
'''

        return self.write_file(f"{name}.py", code)

    # ==========================================
    # CALCULATOR
    # ==========================================

    def create_calculator(self):

        code = '''
while True:

    print("\\nCalculator")

    print("1. Add")
    print("2. Subtract")
    print("3. Multiply")
    print("4. Divide")
    print("5. Exit")

    choice = input("> ")

    if choice == "5":
        break

    a = float(input("First Number: "))
    b = float(input("Second Number: "))

    if choice == "1":
        print("Answer:", a + b)

    elif choice == "2":
        print("Answer:", a - b)

    elif choice == "3":
        print("Answer:", a * b)

    elif choice == "4":
        print("Answer:", a / b)
'''

        return self.write_file("calculator.py", code)

    # ==========================================
    # CHATBOT
    # ==========================================

    def create_chatbot(self):

        code = '''
print("NOVA Chatbot")

while True:

    user = input("You: ")

    if user.lower() == "exit":
        break

    print("NOVA:", "I am still learning.")
'''

        return self.write_file("chatbot.py", code)

    # ==========================================
    # GUESS GAME
    # ==========================================

    def create_guess_game(self):

        code = '''
import random

number = random.randint(1,100)

while True:

    guess = int(input("Guess: "))

    if guess == number:

        print("Correct!")

        break

    elif guess < number:

        print("Too Low")

    else:

        print("Too High")
'''

        return self.write_file("guess_game.py", code)

    # ==========================================
    # NOTES APP
    # ==========================================

    def create_notes(self):

        code = '''
notes = []

while True:

    print("\\nNotes")

    print("1. Add Note")
    print("2. Show Notes")
    print("3. Exit")

    choice = input("> ")

    if choice == "1":

        notes.append(input("Note: "))

    elif choice == "2":

        for i, note in enumerate(notes, 1):

            print(i, note)

    elif choice == "3":

        break
'''

        return self.write_file("notes.py", code)

    # ==========================================
    # TODO APP
    # ==========================================

    def create_todo(self):

        code = '''
tasks = []

while True:

    print("\\nTodo")

    print("1. Add Task")
    print("2. Show Tasks")
    print("3. Exit")

    choice = input("> ")

    if choice == "1":

        tasks.append(input("Task: "))

    elif choice == "2":

        for i, task in enumerate(tasks, 1):

            print(i, task)

    elif choice == "3":

        break
'''

        return self.write_file("todo.py", code)
