import os


class ReactBuilder:

    def write(self, filename, code):

        with open(filename, "w", encoding="utf-8") as f:
            f.write(code)


    def create_project(self, name):

        os.makedirs(name, exist_ok=True)
        os.makedirs(f"{name}/src", exist_ok=True)
        os.makedirs(f"{name}/public", exist_ok=True)

        package = '''{
  "name":"NOVA-react",
  "version":"1.0.0",
  "private":true
}
'''

        app = '''import "./App.css";

function App(){

    return(

        <div className="App">

            <h1>Welcome to NOVA React</h1>

            <p>Your project is ready.</p>

        </div>

    );

}

export default App;
'''

        css = '''
body{

margin:0;

font-family:Arial;

background:#121212;

color:white;

}

.App{

text-align:center;

padding:50px;

}
'''

        index = '''
import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";

const root = ReactDOM.createRoot(
document.getElementById("root")
);

root.render(<App />);
'''

        html = '''<!DOCTYPE html>

<html>

<head>

<meta charset="UTF-8">

<title>NOVA React</title>

</head>

<body>

<div id="root"></div>

</body>

</html>
'''

        readme = f'''# {name}

Generated by NOVA

Install:

npm install

Run:

npm start
'''

        self.write(f"{name}/package.json", package)
        self.write(f"{name}/src/App.js", app)
        self.write(f"{name}/src/App.css", css)
        self.write(f"{name}/src/index.js", index)
        self.write(f"{name}/public/index.html", html)
        self.write(f"{name}/README.md", readme)

        return f"React project '{name}' created."


    def create_portfolio(self):

        return self.create_project("react_portfolio")


    def create_dashboard(self):

        return self.create_project("react_dashboard")


    def create_blog(self):

        return self.create_project("react_blog")


    def create_store(self):

        return self.create_project("react_store")


    def create_school(self):

        return self.create_project("react_school")


    def create_chat(self):

        return self.create_project("react_chat")


    def create_music(self):

        return self.create_project("react_music")


    def create_video(self):

        return self.create_project("react_video")


    def create_trading(self):

        return self.create_project("react_trading")


    def create_ai(self):

        return self.create_project("react_ai")
