import os


class RoboticsBuilder:

    def write(self, filename, code):

        os.makedirs(os.path.dirname(filename), exist_ok=True)

        with open(filename, "w", encoding="utf-8") as f:
            f.write(code)


    def create_project(self, name):

        os.makedirs(name, exist_ok=True)

        self.write(
            f"{name}/README.md",
            f"# {name}\n\nGenerated by NOVA Robotics Builder\n"
        )

        return f"{name} created."


    # ==========================================
    # ROBOT CONTROLLER
    # ==========================================

    def create_robot_controller(self):

        self.create_project("robot_controller")

        code = '''
print("NOVA Robot Controller")
'''

        self.write("robot_controller/main.py", code)

        return "Robot Controller created."


    # ==========================================
    # MOTOR CONTROL
    # ==========================================

    def create_motor_control(self):

        self.create_project("motor_control")

        code = '''
print("Motor Control Template")
'''

        self.write("motor_control/main.py", code)

        return "Motor Control created."


    # ==========================================
    # SENSOR READER
    # ==========================================

    def create_sensor_reader(self):

        self.create_project("sensor_reader")

        code = '''
print("Sensor Reader Template")
'''

        self.write("sensor_reader/main.py", code)

        return "Sensor Reader created."


    # ==========================================
    # CAMERA ROBOT
    # ==========================================

    def create_camera_robot(self):

        self.create_project("camera_robot")

        code = '''
print("Camera Robot Template")
'''

        self.write("camera_robot/main.py", code)

        return "Camera Robot created."


    # ==========================================
    # LINE FOLLOWER
    # ==========================================

    def create_line_follower(self):

        self.create_project("line_follower")

        code = '''
print("Line Follower Robot")
'''

        self.write("line_follower/main.py", code)

        return "Line Follower created."


    # ==========================================
    # OBSTACLE AVOIDANCE
    # ==========================================

    def create_obstacle_avoidance(self):

        self.create_project("obstacle_avoidance")

        code = '''
print("Obstacle Avoidance Robot")
'''

        self.write("obstacle_avoidance/main.py", code)

        return "Obstacle Avoidance created."


    # ==========================================
    # VOICE CONTROL ROBOT
    # ==========================================

    def create_voice_robot(self):

        self.create_project("voice_robot")

        code = '''
print("Voice Controlled Robot")
'''

        self.write("voice_robot/main.py", code)

        return "Voice Robot created."


    # ==========================================
    # DRONE
    # ==========================================

    def create_drone(self):

        self.create_project("drone")

        code = '''
print("Drone Project Template")
'''

        self.write("drone/main.py", code)

        return "Drone project created."


    # ==========================================
    # RASPBERRY PI
    # ==========================================

    def create_raspberry_pi(self):

        self.create_project("raspberry_pi")

        code = '''
print("Raspberry Pi Project")
'''

        self.write("raspberry_pi/main.py", code)

        return "Raspberry Pi project created."


    # ==========================================
    # ARDUINO
    # ==========================================

    def create_arduino(self):

        self.create_project("arduino")

        code = '''
print("Arduino Project")
'''

        self.write("arduino/main.py", code)

        return "Arduino project created."


    # ==========================================
    # SMART HOME
    # ==========================================

    def create_smart_home(self):

        self.create_project("smart_home")

        code = '''
print("Smart Home Automation")
'''

        self.write("smart_home/main.py", code)

        return "Smart Home project created."


    # ==========================================
    # AUTONOMOUS ROBOT
    # ==========================================

    def create_autonomous_robot(self):

        self.create_project("autonomous_robot")

        code = '''
print("Autonomous Robot Template")
'''

        self.write("autonomous_robot/main.py", code)

        return "Autonomous Robot created."
