import os


class SecurityBuilder:

    def write(self, filename, code):

        os.makedirs(os.path.dirname(filename), exist_ok=True)

        with open(filename, "w", encoding="utf-8") as f:

            f.write(code)


    def create_project(self, name):

        os.makedirs(name, exist_ok=True)

        self.write(
            f"{name}/README.md",
            f"# {name}\n\nGenerated by NOVA\n"
        )

        return f"{name} created."


    # ==========================================
    # PASSWORD HASHER
    # ==========================================

    def create_password_hasher(self):

        self.create_project("password_hasher")

        code = '''
import hashlib

password = input("Password: ")

hashed = hashlib.sha256(password.encode()).hexdigest()

print("SHA256:", hashed)
'''

        self.write("password_hasher/main.py", code)

        return "Password Hasher created."


    # ==========================================
    # FILE HASHER
    # ==========================================

    def create_file_hasher(self):

        self.create_project("file_hasher")

        code = '''
import hashlib

filename = input("File: ")

with open(filename,"rb") as f:

    print(hashlib.sha256(f.read()).hexdigest())
'''

        self.write("file_hasher/main.py", code)

        return "File Hasher created."


    # ==========================================
    # RANDOM PASSWORD
    # ==========================================

    def create_password_generator(self):

        self.create_project("password_generator")

        code = '''
import secrets
import string

alphabet = string.ascii_letters + string.digits

password = "".join(
    secrets.choice(alphabet)
    for _ in range(20)
)

print(password)
'''

        self.write("password_generator/main.py", code)

        return "Password Generator created."


    # ==========================================
    # JWT TEMPLATE
    # ==========================================

    def create_jwt(self):

        self.create_project("jwt_template")

        code = '''
print("Install PyJWT")

print("JWT Authentication Template")
'''

        self.write("jwt_template/main.py", code)

        return "JWT Template created."


    # ==========================================
    # LOGIN SYSTEM
    # ==========================================

    def create_login(self):

        self.create_project("login_system")

        code = '''
username = input("Username: ")

password = input("Password: ")

print("Login Template")
'''

        self.write("login_system/main.py", code)

        return "Login System created."


    # ==========================================
    # API KEY TEMPLATE
    # ==========================================

    def create_api_key(self):

        self.create_project("api_key_project")

        code = '''
import secrets

print(secrets.token_hex(32))
'''

        self.write("api_key_project/main.py", code)

        return "API Key Generator created."


    # ==========================================
    # TOKEN GENERATOR
    # ==========================================

    def create_token(self):

        self.create_project("token_generator")

        code = '''
import secrets

print(secrets.token_urlsafe(32))
'''

        self.write("token_generator/main.py", code)

        return "Token Generator created."


    # ==========================================
    # ENCRYPTION TEMPLATE
    # ==========================================

    def create_encryption(self):

        self.create_project("encryption_template")

        code = '''
print("Encryption Project Template")
'''

        self.write("encryption_template/main.py", code)

        return "Encryption Template created."


    # ==========================================
    # DECRYPTION TEMPLATE
    # ==========================================

    def create_decryption(self):

        self.create_project("decryption_template")

        code = '''
print("Decryption Project Template")
'''

        self.write("decryption_template/main.py", code)

        return "Decryption Template created."


    # ==========================================
    # SECURITY SCANNER
    # ==========================================

    def create_security_scanner(self):

        self.create_project("security_scanner")

        code = '''
print("Security Scanner Template")
'''

        self.write("security_scanner/main.py", code)

        return "Security Scanner created."
