import os


class TestingBuilder:

    def write(self, filename, code):

        os.makedirs(os.path.dirname(filename), exist_ok=True)

        with open(filename, "w", encoding="utf-8") as f:

            f.write(code)


    def create_project(self, name):

        os.makedirs(name, exist_ok=True)

        self.write(
            f"{name}/README.md",
            f"# {name}\n\nGenerated by NOVA\n"
        )

        return f"{name} created."


    # ==========================================
    # UNIT TEST
    # ==========================================

    def create_unit_test(self):

        self.create_project("unit_test")

        code = '''
import unittest

class TestMath(unittest.TestCase):

    def test_add(self):

        self.assertEqual(2+2,4)

if __name__=="__main__":

    unittest.main()
'''

        self.write("unit_test/test_math.py", code)

        return "Unit Test created."


    # ==========================================
    # PYTEST
    # ==========================================

    def create_pytest(self):

        self.create_project("pytest_project")

        code = '''
def add(a,b):

    return a+b

def test_add():

    assert add(5,5)==10
'''

        self.write("pytest_project/test_app.py", code)

        return "Pytest project created."


    # ==========================================
    # API TEST
    # ==========================================

    def create_api_test(self):

        self.create_project("api_test")

        code = '''
import requests

response=requests.get("https://example.com")

print(response.status_code)
'''

        self.write("api_test/main.py", code)

        return "API Test created."


    # ==========================================
    # LOAD TEST
    # ==========================================

    def create_load_test(self):

        self.create_project("load_test")

        code = '''
print("Load Test Template")
'''

        self.write("load_test/main.py", code)

        return "Load Test created."


    # ==========================================
    # SECURITY TEST
    # ==========================================

    def create_security_test(self):

        self.create_project("security_test")

        code = '''
print("Security Test Template")
'''

        self.write("security_test/main.py", code)

        return "Security Test created."


    # ==========================================
    # DATABASE TEST
    # ==========================================

    def create_database_test(self):

        self.create_project("database_test")

        code = '''
print("Database Test Template")
'''

        self.write("database_test/main.py", code)

        return "Database Test created."


    # ==========================================
    # WEB TEST
    # ==========================================

    def create_web_test(self):

        self.create_project("web_test")

        code = '''
print("Web Test Template")
'''

        self.write("web_test/main.py", code)

        return "Web Test created."


    # ==========================================
    # MOBILE TEST
    # ==========================================

    def create_mobile_test(self):

        self.create_project("mobile_test")

        code = '''
print("Mobile Test Template")
'''

        self.write("mobile_test/main.py", code)

        return "Mobile Test created."


    # ==========================================
    # AI TEST
    # ==========================================

    def create_ai_test(self):

        self.create_project("ai_test")

        code = '''
print("AI Test Template")
'''

        self.write("ai_test/main.py", code)

        return "AI Test created."


    # ==========================================
    # PERFORMANCE TEST
    # ==========================================

    def create_performance_test(self):

        self.create_project("performance_test")

        code = '''
print("Performance Test Template")
'''

        self.write("performance_test/main.py", code)

        return "Performance Test created."
