import os

PROJECTS = os.path.expanduser("~/NOVA/generated_projects")

os.makedirs(PROJECTS, exist_ok=True)


def create_website(name):

    folder = os.path.join(
        PROJECTS,
        name.replace(" ", "_").lower()
    )

    os.makedirs(folder, exist_ok=True)

    html = """<!DOCTYPE html>
<html>
<head>
    <title>My Website</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>

<h1>Welcome to My Website</h1>

<p>Generated by NOVA AI.</p>

<script src="script.js"></script>

</body>
</html>
"""

    css = """body{
    background:#111;
    color:white;
    font-family:Arial;
    text-align:center;
    padding-top:100px;
}

h1{
    color:#00ffff;
}
"""

    js = """console.log("NOVA Website Loaded");"""

    with open(os.path.join(folder, "index.html"), "w") as f:
        f.write(html)

    with open(os.path.join(folder, "style.css"), "w") as f:
        f.write(css)

    with open(os.path.join(folder, "script.js"), "w") as f:
        f.write(js)

    return f"Website '{name}' created successfully in {folder}."


def portfolio():
    return create_website("Portfolio")


def landing_page():
    return create_website("Landing Page")


def ecommerce():
    return create_website("Ecommerce")
