from .project_manager import ProjectManager
from .project_registry import ProjectRegistry


class AIGenerator:

    def __init__(self):

        self.pm = ProjectManager()
        self.registry = ProjectRegistry()

    def create(self, name):

        project = self.pm.create_project(name)

        self.pm.create_folder(project, "models")
        self.pm.create_folder(project, "data")
        self.pm.create_folder(project, "prompts")

        main_py = f'''"""
{name}
Generated by NOVA AI
"""

class AI:

    def __init__(self):

        self.name = "{name}"

    def chat(self, message):

        return f"{{self.name}} received: {{message}}"


def main():

    ai = AI()

    print("=== " + ai.name + " ===")

    while True:

        text = input("You: ")

        if text.lower() in ["exit", "quit"]:

            break

        print(ai.chat(text))


if __name__ == "__main__":

    main()
'''

        requirements = """
requests
"""

        prompt = """
You are a helpful AI assistant.
"""

        readme = f"""# {name}

Generated by NOVA AI

Folders:

- models/
- data/
- prompts/

Run:

python main.py
"""

        self.pm.write(project, "main.py", main_py)
        self.pm.write(project, "requirements.txt", requirements)
        self.pm.write(project, "prompts/system_prompt.txt", prompt)
        self.pm.write(project, "README.md", readme)

        self.registry.add(name, "ai")

        return f"AI project created successfully: {project}"
