from .project_manager import ProjectManager
from .project_registry import ProjectRegistry


class APIGenerator:

    def __init__(self):

        self.pm = ProjectManager()
        self.registry = ProjectRegistry()

    def create(self, name):

        project = self.pm.create_project(name)

        self.pm.create_folder(project, "routes")
        self.pm.create_folder(project, "models")
        self.pm.create_folder(project, "config")

        app_py = '''from flask import Flask, jsonify

app = Flask(__name__)

@app.route("/")
def home():

    return jsonify({
        "name":"NOVA API",
        "status":"online"
    })

@app.route("/health")
def health():

    return jsonify({
        "status":"healthy"
    })

if __name__ == "__main__":

    app.run(debug=True)
'''

        requirements = """flask"""

        readme = f"""# {name}

Generated by NOVA AI

Run:

pip install -r requirements.txt

python app.py
"""

        self.pm.write(project, "app.py", app_py)
        self.pm.write(project, "requirements.txt", requirements)
        self.pm.write(project, "README.md", readme)
        self.pm.write(project, "routes/__init__.py", "")
        self.pm.write(project, "models/__init__.py", "")
        self.pm.write(project, "config/__init__.py", "")

        self.registry.add(name, "api")

        return f"API created successfully: {project}"
