from .project_manager import ProjectManager
from .project_registry import ProjectRegistry


class ChatbotGenerator:

    def __init__(self):

        self.pm = ProjectManager()
        self.registry = ProjectRegistry()

    def create(self, name):

        project = self.pm.create_project(name)

        self.pm.create_folder(project, "memory")

        bot_py = f'''class {name}:

    def __init__(self):

        self.name = "{name}"

    def reply(self, message):

        message = message.lower()

        if "hello" in message:
            return "Hello!"

        if "how are you" in message:
            return "I'm doing great."

        return "I am still learning."


bot = {name}()

while True:

    text = input("You: ")

    if text.lower() in ["exit", "quit"]:

        break

    print(bot.reply(text))
'''

        readme = f"""# {name}

Generated by NOVA AI

Run:

python bot.py
"""

        self.pm.write(project, "bot.py", bot_py)
        self.pm.write(project, "memory/history.json", "[]")
        self.pm.write(project, "README.md", readme)

        self.registry.add(name, "chatbot")

        return f"Chatbot created successfully: {project}"
