# ==========================================================
# NOVA FULLSTACK GENERATOR 2.0
# developer/code_engine/fullstack_generator.py
# Part 1/5
# ==========================================================

from .project_manager import ProjectManager
from .project_registry import ProjectRegistry


class FullStackGenerator:

    def __init__(self):

        self.pm = ProjectManager()

        self.registry = ProjectRegistry()


    # ======================================================
    # CREATE FULLSTACK PROJECT
    # ======================================================

    def create(self, name):

        project = self.pm.create_project(name)


        # Main folders

        self.pm.create_folder(
            project,
            "frontend"
        )

        self.pm.create_folder(
            project,
            "backend"
        )

        self.pm.create_folder(
            project,
            "database"
        )

        self.pm.create_folder(
            project,
            "docs"
        )        # ======================================================
        # FRONTEND STRUCTURE (React/Vite STYLE)
        # ======================================================

        self.pm.create_folder(
            project,
            "frontend/src"
        )

        self.pm.create_folder(
            project,
            "frontend/public"
        )


        package_json = f"""
{{
  "name": "{name.lower()}-frontend",
  "version": "1.0.0",
  "private": true,
  "scripts": {{
    "dev": "vite",
    "build": "vite build"
  }},
  "dependencies": {{
    "react": "latest",
    "react-dom": "latest"
  }}
}}
"""


        index_html = f"""
<!DOCTYPE html>
<html>

<head>

<title>{name}</title>

</head>

<body>

<div id="root"></div>

<script type="module" src="/src/main.jsx"></script>

</body>

</html>
"""


        app_jsx = f"""
export default function App() {{

    return (

        <div>

            <h1>{name}</h1>

            <p>
            Generated by NOVA FullStack AI
            </p>

        </div>

    );

}}
"""


        main_jsx = """
import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";


ReactDOM.createRoot(
    document.getElementById("root")
).render(
    <App />
);
"""        # ======================================================
        # BACKEND STRUCTURE (FASTAPI)
        # ======================================================

        self.pm.create_folder(
            project,
            "backend/api"
        )


        app_py = f"""
from fastapi import FastAPI


app = FastAPI(
    title="{name} API"
)


@app.get("/")
def home():

    return {{

        "project": "{name}",

        "message": "NOVA FastAPI backend online"

    }}


@app.get("/health")
def health():

    return {{

        "status": "healthy"

    }}
"""


        requirements = """
fastapi
uvicorn
"""


        api_init = """
# API routes
"""


        # ======================================================
        # DATABASE
        # ======================================================

        database_py = """
import sqlite3


def connect():

    return sqlite3.connect(
        "database.db"
    )


def create_database():

    db = connect()

    db.close()
"""


        env_example = """
DATABASE_URL=sqlite:///database.db

API_KEY=your_key_here
"""        # ======================================================
        # WRITE FRONTEND FILES
        # ======================================================

        self.pm.write(
            project,
            "frontend/package.json",
            package_json
        )

        self.pm.write(
            project,
            "frontend/index.html",
            index_html
        )

        self.pm.write(
            project,
            "frontend/src/App.jsx",
            app_jsx
        )

        self.pm.write(
            project,
            "frontend/src/main.jsx",
            main_jsx
        )


        # ======================================================
        # WRITE BACKEND FILES
        # ======================================================

        self.pm.write(
            project,
            "backend/app.py",
            app_py
        )

        self.pm.write(
            project,
            "backend/requirements.txt",
            requirements
        )

        self.pm.write(
            project,
            "backend/api/__init__.py",
            api_init
        )


        # ======================================================
        # WRITE DATABASE FILES
        # ======================================================

        self.pm.write(
            project,
            "database/database.py",
            database_py
        )


        # ======================================================
        # ENVIRONMENT FILE
        # ======================================================

        self.pm.write(
            project,
            ".env.example",
            env_example
        )        # ======================================================
        # DOCKER CONFIGURATION
        # ======================================================

        docker_compose = f"""
services:

  frontend:

    build: ./frontend

    ports:

      - "5173:5173"


  backend:

    build: ./backend

    ports:

      - "8000:8000"
"""


        # ======================================================
        # README
        # ======================================================

        readme = f"""
# {name}

Generated by NOVA FullStack AI


## Structure

frontend/
- React application


backend/
- FastAPI server


database/
- Database layer



## Start Backend

cd backend

pip install -r requirements.txt

uvicorn app:app --reload



## Start Frontend

cd frontend

npm install

npm run dev
"""


        self.pm.write(
            project,
            "docker-compose.yml",
            docker_compose
        )


        self.pm.write(
            project,
            "README.md",
            readme
        )


        # ======================================================
        # REGISTER PROJECT
        # ======================================================

        self.registry.add(
            name,
            "fullstack"
        )


        return (
            f"FullStack project created successfully!\n"
            f"Name: {name}\n"
            f"Location: {project}"
        )
