from .project_manager import ProjectManager
from .project_registry import ProjectRegistry


class ReactGenerator:

    def __init__(self):

        self.pm = ProjectManager()
        self.registry = ProjectRegistry()

    def create(self, name):

        project = self.pm.create_project(name)

        self.pm.create_folder(project, "src")
        self.pm.create_folder(project, "public")

        package_json = f'''{{
  "name": "{name.lower()}",
  "private": true,
  "version": "1.0.0",
  "scripts": {{
    "dev": "vite",
    "build": "vite build"
  }}
}}
'''

        main_jsx = """import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";

ReactDOM.createRoot(document.getElementById("root")).render(
    <App />
);
"""

        app_jsx = f"""export default function App() {{
    return (
        <div>
            <h1>Welcome to {name}</h1>
            <p>Generated by NOVA AI</p>
        </div>
    );
}}
"""

        index_html = """<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>React App</title>
</head>
<body>

<div id="root"></div>

<script type="module" src="/src/main.jsx"></script>

</body>
</html>
"""

        self.pm.write(project, "package.json", package_json)
        self.pm.write(project, "index.html", index_html)
        self.pm.write(project, "src/main.jsx", main_jsx)
        self.pm.write(project, "src/App.jsx", app_jsx)

        self.registry.add(name, "react")

        return f"React project created: {project}"
