from .project_manager import ProjectManager
from .project_registry import ProjectRegistry


class WebAppGenerator:

    def __init__(self):

        self.pm = ProjectManager()
        self.registry = ProjectRegistry()

    def create(self, name):

        project = self.pm.create_project(name)

        self.pm.create_folder(project, "templates")
        self.pm.create_folder(project, "static")
        self.pm.create_folder(project, "static/css")
        self.pm.create_folder(project, "static/js")
        self.pm.create_folder(project, "static/images")

        app_py = f'''from flask import Flask, render_template

app = Flask(__name__)

@app.route("/")
def home():
    return render_template("index.html")

if __name__ == "__main__":
    app.run(debug=True)
'''

        html = f"""<!DOCTYPE html>
<html>
<head>
    <title>{name}</title>
    <link rel="stylesheet" href="/static/css/style.css">
</head>
<body>

<h1>Welcome to {name}</h1>

<p>Generated by NOVA AI.</p>

<script src="/static/js/app.js"></script>

</body>
</html>
"""

        css = """
body{
    font-family:Arial;
    background:#f5f5f5;
    text-align:center;
    padding:40px;
}
"""

        js = """
console.log("NOVA Web App Loaded");
"""

        requirements = """
flask
"""

        readme = f"""# {name}

Generated by NOVA AI

Run:

python app.py
"""

        self.pm.write(project, "app.py", app_py)
        self.pm.write(project, "templates/index.html", html)
        self.pm.write(project, "static/css/style.css", css)
        self.pm.write(project, "static/js/app.js", js)
        self.pm.write(project, "requirements.txt", requirements)
        self.pm.write(project, "README.md", readme)

        self.registry.add(name, "webapp")

        return f"Web App created successfully: {project}"
