# ==========================================================
# NOVA WEBSITE GENERATOR
# developer/code_engine/website_generator.py
# Part 1/5
# ==========================================================

from .project_manager import ProjectManager
from .project_registry import ProjectRegistry
from .template_manager import TemplateManager


class WebsiteGenerator:

    def __init__(self):

        # Project manager
        self.pm = ProjectManager()

        # Project registry
        self.registry = ProjectRegistry()

        # HTML templates
        self.templates = TemplateManager()

    # ======================================================
    # CREATE WEBSITE
    # ======================================================

    def create(self, name):

        # Create project
        project = self.pm.create_project(name)

        # Create folders
        self.pm.create_folder(project, "css")
        self.pm.create_folder(project, "js")
        self.pm.create_folder(project, "images")

        # Load HTML template
        index_html = self.templates.template(
            "websites",
            "index.html"
        )

        # Fallback if template is missing
        if index_html is None:

            index_html = """
<!DOCTYPE html>
<html>
<head>
<title>{{PROJECT_NAME}}</title>
</head>
<body>

<h1>{{PROJECT_NAME}}</h1>

<p>Generated by NOVA AI</p>

</body>
</html>
"""

        # Replace placeholders
        index_html = index_html.replace(
            "{{PROJECT_NAME}}",
            name
        )        # ======================================================
        # DEFAULT CSS
        # ======================================================

        style_css = """
*{

    margin:0;

    padding:0;

    box-sizing:border-box;

}

body{

    font-family:Arial, Helvetica, sans-serif;

    background:#f5f5f5;

    color:#222;

}

header{

    background:#1976d2;

    color:white;

    padding:40px;

    text-align:center;

}

main{

    padding:40px;

}

h1{

    margin-bottom:10px;

}

p{

    line-height:1.6;

}
"""


        # ======================================================
        # DEFAULT JAVASCRIPT
        # ======================================================

        app_js = f"""
console.log("{name} loaded successfully.");

document.addEventListener("DOMContentLoaded", function(){{

    console.log("NOVA AI Website Ready");

}});
"""


        # ======================================================
        # README
        # ======================================================

        readme = f"""# {name}

Generated by NOVA AI

Project Type:
Website

Folders

css/
js/
images/

Files

index.html
css/style.css
js/app.js

To preview:

Open index.html in your browser.
"""        # ======================================================
        # WRITE PROJECT FILES
        # ======================================================

        self.pm.write(
            project,
            "index.html",
            index_html
        )

        self.pm.write(
            project,
            "css/style.css",
            style_css
        )

        self.pm.write(
            project,
            "js/app.js",
            app_js
        )

        self.pm.write(
            project,
            "README.md",
            readme
        )


        # ======================================================
        # REGISTER PROJECT
        # ======================================================

        self.registry.add(
            name,
            "website"
        )        # ======================================================
        # CREATE EXTRA PROJECT FILES
        # ======================================================

        gitignore = """
# Python
__pycache__/
*.pyc

# Logs
*.log

# Environment
.env
venv/

# IDE
.vscode/
.idea/

# OS
.DS_Store
Thumbs.db
"""

        license_text = f"""MIT License

Copyright (c) 2026 {name}

Permission is hereby granted, free of charge,
to any person obtaining a copy of this software
to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies.
"""

        self.pm.write(
            project,
            ".gitignore",
            gitignore
        )

        self.pm.write(
            project,
            "LICENSE",
            license_text
        )

        print(f"Website '{name}' created successfully.")        # ======================================================
        # FINISH
        # ======================================================

        return (
            f"Website created successfully!\n"
            f"Name: {name}\n"
            f"Location: {project}"
        )
